package quebec.lanaudiere.essence;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.location.*;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class MainActivity extends Activity {
 private static final int REQ_LOCATION=101,REQ_NOTIFICATIONS=102; private static final String CHANNEL_ID="best_price";
 private LinearLayout root,results; private TextView status,bestBanner; private Spinner fuelSpinner,sortSpinner,radiusSpinner; private final int blue=Color.rgb(0,63,165),pale=Color.rgb(247,251,255);
 private final Set<String> lanaudiereCities=new HashSet<>(Arrays.asList("berthierville","charlemagne","chertsey","crabtree","entrelacs","joliette","lanoraie","l'assomption","l'épiphanie","lavaltrie","mandeville","mascouche","notre-dame-de-la-merci","notre-dame-de-lourdes","notre-dame-des-prairies","rawdon","repentigny","saint-alexis","saint-alphonse-rodriguez","saint-ambroise-de-kildare","saint-barthélemy","saint-calixte","saint-charles-borromée","saint-côme","saint-cuthbert","saint-damien","saint-didace","saint-donat","saint-esprit","saint-félix-de-valois","saint-gabriel","saint-gabriel-de-brandon","saint-ignace-de-loyola","saint-jacques","saint-jean-de-matha","saint-liguori","saint-lin-laurentides","saint-michel-des-saints","saint-norbert","saint-paul","saint-pierre","saint-roch-de-l'achigan","saint-roch-ouest","saint-sulpice","saint-thomas","sainte-béatrix","sainte-élisabeth","sainte-émélie-de-l'énergie","sainte-geneviève-de-berthier","sainte-julienne","sainte-marcelline-de-kildare","sainte-marie-salomé","sainte-mélanie","terrebonne","la visitation-de-l'île-dupas"));
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(pale);getWindow().setNavigationBarColor(pale);int ui=View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;if(Build.VERSION.SDK_INT>=26)ui|=View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;getWindow().getDecorView().setSystemUiVisibility(ui);createNotificationChannel();buildUi();requestPermissionsAndLocate();}
 private void buildUi(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(28));root.setBackgroundColor(pale);scroll.addView(root);root.setOnApplyWindowInsetsListener((v,i)->{int t,b;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=i.getInsets(WindowInsets.Type.systemBars());t=x.top;b=x.bottom;}else{t=i.getSystemWindowInsetTop();b=i.getSystemWindowInsetBottom();}v.setPadding(dp(18),dp(18)+t,dp(18),dp(28)+b);return i;});root.addView(text("ESSENCE LANAUDIÈRE",28,true,blue));TextView sub=text("Prix autour de moi • GPS • meilleur prix",15,false,Color.DKGRAY);sub.setPadding(0,dp(4),0,dp(14));root.addView(sub);bestBanner=text("📍 Localisation en cours…",18,true,Color.WHITE);bestBanner.setPadding(dp(16),dp(14),dp(16),dp(14));bestBanner.setBackground(round(blue,18));root.addView(bestBanner,mp(dp(8)));LinearLayout c=card();c.addView(label("Carburant"));fuelSpinner=spinner(new String[]{"Ordinaire","Super","Diesel"});c.addView(fuelSpinner);c.addView(label("Classement"));sortSpinner=spinner(new String[]{"Moins cher","Plus proche","Meilleur compromis"});sortSpinner.setSelection(1);c.addView(sortSpinner);c.addView(label("Rayon"));radiusSpinner=spinner(new String[]{"5 km","10 km","20 km","30 km"});radiusSpinner.setSelection(3);c.addView(radiusSpinner);Button r=button("ACTUALISER LES PRIX");r.setOnClickListener(v->locateAndLoad());c.addView(r,mp(dp(12)));root.addView(c,mp(dp(12)));status=text("Les prix proviennent de Régie Essence Québec et sont présentés via Gas Québec.",13,false,Color.DKGRAY);root.addView(status);results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);root.addView(results);LinearLayout refs=card();refs.addView(text("Références",18,true,blue));Button caa=secondaryButton("CAA‑QUÉBEC • INFO ESSENCE");caa.setOnClickListener(v->openUrl("https://www.caaquebec.com/fr/mobilite/info-essence"));refs.addView(caa);Button regie=secondaryButton("RÉGIE ESSENCE QUÉBEC");regie.setOnClickListener(v->openUrl("https://regieessencequebec.ca"));refs.addView(regie);TextView note=text("CAA‑Québec sert de référence régionale. Le classement utilise les prix publiés par les commerçants à la Régie de l’énergie. Vérifie toujours le prix à la pompe.",12,false,Color.GRAY);note.setPadding(0,dp(10),0,0);refs.addView(note);root.addView(refs,mp(dp(12)));TextView footer=text("Créé par 🚨🚨adamrheaume@gmail.com 🚨🚨",13,true,Color.DKGRAY);footer.setGravity(Gravity.CENTER);footer.setPadding(dp(4),dp(10),dp(4),dp(12));root.addView(footer,mp(0));setContentView(scroll);root.requestApplyInsets();}
 private boolean hasLocationPermission(){return checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED;}
 private void requestPermissionsAndLocate(){if(!hasLocationPermission()){bestBanner.setText("📍 Autorisation GPS requise");status.setText("Autorise la localisation pour afficher les stations autour de toi.");requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},REQ_LOCATION);}else{locateAndLoad();requestNotificationPermissionIfNeeded();}}
 private void requestNotificationPermissionIfNeeded(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ_NOTIFICATIONS);}
 @Override public void onRequestPermissionsResult(int q,String[] p,int[] g){super.onRequestPermissionsResult(q,p,g);if(q==REQ_LOCATION){if(hasLocationPermission()){locateAndLoad();requestNotificationPermissionIfNeeded();}else{bestBanner.setText("GPS requis pour trouver les stations proches");status.setText("Autorise la localisation dans les paramètres de l'application.");}}}
 private void locateAndLoad(){if(!hasLocationPermission()){requestPermissionsAndLocate();return;}bestBanner.setText("📍 Recherche de ta position…");status.setText("Recherche GPS + réseau en cours…");LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);boolean ge=lm.isProviderEnabled(LocationManager.GPS_PROVIDER),ne=lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER);if(!ge&&!ne){bestBanner.setText("⚠️ Localisation du téléphone désactivée");try{startActivity(new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS));}catch(Exception ignored){}return;}Location best=null;for(String p:Arrays.asList(LocationManager.NETWORK_PROVIDER,LocationManager.GPS_PROVIDER))try{if(lm.isProviderEnabled(p)){Location l=lm.getLastKnownLocation(p);if(l!=null&&(best==null||l.getTime()>best.getTime()))best=l;}}catch(Exception ignored){}if(best!=null&&System.currentTimeMillis()-best.getTime()<900000){loadStations(best);return;}final Location fallback=best;Handler h=new Handler(Looper.getMainLooper());boolean[] done={false};LocationListener listener=new LocationListener(){public void onLocationChanged(Location l){if(done[0]||l==null)return;done[0]=true;h.removeCallbacksAndMessages(null);try{lm.removeUpdates(this);}catch(Exception ignored){}loadStations(l);}public void onProviderEnabled(String p){}public void onProviderDisabled(String p){}public void onStatusChanged(String p,int s,Bundle e){}};try{if(ne)lm.requestLocationUpdates(LocationManager.NETWORK_PROVIDER,0,0,listener,Looper.getMainLooper());if(ge)lm.requestLocationUpdates(LocationManager.GPS_PROVIDER,0,0,listener,Looper.getMainLooper());h.postDelayed(()->{if(done[0])return;done[0]=true;try{lm.removeUpdates(listener);}catch(Exception ignored){}if(fallback!=null){bestBanner.setText("📍 Position approximative utilisée");loadStations(fallback);}else{bestBanner.setText("⚠️ Position introuvable");status.setText("Active la localisation précise puis actualise.");}},8000);}catch(Exception e){if(fallback!=null)loadStations(fallback);else bestBanner.setText("Impossible d’obtenir la position");}}
 private void loadStations(Location l){bestBanner.setText("⛽ Recherche des prix dans Lanaudière…");results.removeAllViews();String fuel=new String[]{"ordinaire","super","diesel"}[fuelSpinner.getSelectedItemPosition()],sort=new String[]{"price","distance","value"}[sortSpinner.getSelectedItemPosition()];int radius=new int[]{5,10,20,30}[radiusSpinner.getSelectedItemPosition()];String u=String.format(Locale.US,"https://www.gasquebec.ca/api/stations/nearby?lat=%.6f&lng=%.6f&radius=%d&fuelType=%s&limit=50&sort=%s",l.getLatitude(),l.getLongitude(),radius,fuel,sort);new Thread(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(10000);c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","EssenceLanaudiere/1.0 Android");int code=c.getResponseCode();if(code!=200)throw new IOException("Erreur de données ("+code+")");JSONObject o=new JSONObject(readAll(c.getInputStream()));JSONArray a=o.optJSONArray("stations");String source=parseSourceName(o.opt("source"));List<Station> ss=new ArrayList<>();if(a!=null)for(int i=0;i<a.length();i++){JSONObject s=a.getJSONObject(i);String city=s.optString("city","");if(!isLanaudiere(city)||s.isNull("price"))continue;ss.add(new Station(s.optString("name","Station"),s.optString("address",""),city,s.optDouble("lat"),s.optDouble("lng"),s.optDouble("price"),s.optDouble("distanceKm")));}sortStations(ss,sort);runOnUiThread(()->showStations(ss,source,fuel,sort));}catch(Exception e){runOnUiThread(()->{bestBanner.setText("⚠️ Prix indisponibles");status.setText(e.getMessage()==null?"Impossible de joindre la source de prix.":e.getMessage());});}}).start();}
 private String parseSourceName(Object v){if(v instanceof JSONObject){String n=((JSONObject)v).optString("name","").trim();return n.isEmpty()?"Régie essence Québec":n;}String raw=v==null?"":String.valueOf(v).trim();if(raw.startsWith("{")&&raw.endsWith("}"))try{String n=new JSONObject(raw).optString("name","").trim();if(!n.isEmpty())return n;}catch(JSONException ignored){}return raw.isEmpty()||"null".equalsIgnoreCase(raw)?"Régie essence Québec":raw;}
 private void sortStations(List<Station>s,String sort){if("distance".equals(sort))s.sort(Comparator.comparingDouble(x->x.distance));else if("price".equals(sort))s.sort(Comparator.comparingDouble((Station x)->x.price).thenComparingDouble(x->x.distance));else s.sort(Comparator.comparingDouble((Station x)->x.price+x.distance).thenComparingDouble(x->x.distance));}
 private boolean isLanaudiere(String city){return lanaudiereCities.contains(city.trim().toLowerCase(Locale.CANADA_FRENCH).replace('’','\''));}
 private void showStations(List<Station>s,String source,String fuel,String sort){results.removeAllViews();String order="distance".equals(sort)?" • du plus près au plus loin":"price".equals(sort)?" • du moins cher au plus cher":" • meilleur compromis prix/distance";status.setText("Source : "+source+order+" • prix récents, vérifie le prix à la pompe.");if(s.isEmpty()){bestBanner.setText("Aucune station de Lanaudière trouvée dans ce rayon");return;}Station cheap=Collections.min(s,Comparator.comparingDouble(x->x.price));bestBanner.setText(String.format(Locale.CANADA_FRENCH,"🏆 MOINS CHER : %.1f ¢/L • %s • %.1f km",cheap.price,cheap.name,cheap.distance));notifyBest(cheap,fuel);int rank=1;for(Station x:s){LinearLayout c=card();LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(text("#"+rank,16,true,x==cheap?blue:Color.DKGRAY),new LinearLayout.LayoutParams(dp(38),-2));top.addView(text(x.name,17,true,Color.rgb(25,25,25)),new LinearLayout.LayoutParams(0,-2,1));top.addView(text(String.format(Locale.CANADA_FRENCH,"%.1f ¢",x.price),21,true,blue));c.addView(top);c.addView(text(x.address+(x.city.isEmpty()?"":" • "+x.city),13,false,Color.DKGRAY));c.addView(text(String.format(Locale.CANADA_FRENCH,"📍 %.1f km",x.distance),14,true,Color.DKGRAY));Button route=secondaryButton("ITINÉRAIRE");route.setOnClickListener(v->openMap(x));c.addView(route);results.addView(c,mp(dp(10)));rank++;}}
 private void openMap(Station s){Uri u=Uri.parse("geo:"+s.lat+","+s.lng+"?q="+s.lat+","+s.lng+"("+Uri.encode(s.name)+")");try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){openUrl("https://www.google.com/maps/search/?api=1&query="+s.lat+","+s.lng);}}
 private void openUrl(String u){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}
 private void notifyBest(Station s,String fuel){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)return;Notification n=new Notification.Builder(this,CHANNEL_ID).setSmallIcon(R.drawable.ic_launcher).setContentTitle("Essence Lanaudière • meilleur prix").setContentText(String.format(Locale.CANADA_FRENCH,"%.1f ¢/L chez %s • %.1f km",s.price,s.name,s.distance)).setAutoCancel(true).build();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(7,n);}
 private void createNotificationChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL_ID,"Meilleur prix d'essence",NotificationManager.IMPORTANCE_DEFAULT);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
 private String readAll(InputStream in)throws IOException{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)o.write(b,0,n);return o.toString(StandardCharsets.UTF_8.name());}
 private LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(14),dp(14),dp(14),dp(14));l.setBackground(round(Color.WHITE,18));l.setElevation(dp(2));return l;}private TextView label(String s){TextView t=text(s,12,true,Color.GRAY);t.setPadding(0,dp(8),0,dp(3));return t;}private Spinner spinner(String[]a){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));return s;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(round(blue,14));return b;}private Button secondaryButton(String s){Button b=new Button(this);b.setText(s);b.setTextColor(blue);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(round(Color.rgb(233,242,255),14));return b;}private TextView text(String s,int z,boolean bold,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams mp(int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=b;return p;}private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
 static class Station{final String name,address,city;final double lat,lng,price,distance;Station(String n,String a,String c,double la,double ln,double p,double d){name=n;address=a;city=c;lat=la;lng=ln;price=p;distance=d;}}
}
