plugins {
    id 'com.android.application'
    id 'com.chaquo.python'
}

android {
    namespace 'quebec.cast.hisense'
    compileSdk 35

    defaultConfig {
        applicationId 'quebec.cast.hisense'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '5.0'
        ndk { abiFilters 'arm64-v8a' }
        python {
            version '3.13'
            pip {
                install 'paho-mqtt==2.1.0'
                install 'PyYAML==6.0.3'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}
