#!/usr/bin/env python3
import base64,zlib,json,subprocess,pathlib,re
from concurrent.futures import ThreadPoolExecutor,as_completed
B64='eNqVWE2PG7kR/Sv0HDw2MjacRfaSm6QZzZfkUUYaDIxgEZS6SxIhNtkm2ZLbC99zz5/w5JJr7kL+Vx5b3rWbbHnlw2gaEqtZrHr16hV/Pdlynku9PPmr+PuvJ2S9dB7PJ9MVaUlitiWpT87EiZdecfjhnalOLYupl0oJv2Jxp/nk05k4ynhoTSFmK+nE2BSsPYxj25HR7DzZll2voI+cx0v7tiYtejkVrrX6xcWGbe1XOJa4FufmZfMprr1YGCtwgPhFg92TkprFuTRtf/ucUeU42IiR2XAuxny08QzBmZgtW2EWjXVseaG80eLGrNp2AxwqbDhk3kc42IqZ0XK58kmoaUNLFpdkc462t5WqxZhyfJ4zl6qObXtsjSukX7XsQqz0qRePhPx4I8bSOUEha0BJ9IYhwVpcAQrtsFkmOJ5EamXxJDWJCVsr2xnGBqZypHPxjsm62HZmYyyNydq6Ix835BDVsaWP4rkYGDWXLAYEF8m37EdVtk5CMpbZihD2fjVXu6fW+q+gSnZEBsWIl6zz9plQIUh96uJFLqYrZksxYKReB9DeVR5Jr/Ij7RDNBWcJNGZUK+B9upWL6OTAk41XnwN1f8LrqUbYbqqQJ9GXPOd2Jf75zdmbN2/ElanSHH19RctkWjJnK8XuWIOGJQLwL62pAIiHMja8J5eREkPk1Ldrvx/2aYz71qxZi3tDSRxvOcD2wc4phlQT/jEXxkp2IXkPKRJlIcbZpaUtAnWgAK79qQs1bDvrvm8pFxOSTnEdM4buLBrQLZWKfcwwrEGWjlk8glPXXP+I8Y2pG3TWYiQXiY+jao2yMcU8Ci9T5eWiUmKAAquPtBoay4Cc6C18+ESwknzCCxob7WmJdhL1G9FDw2lSis7QTUS9nBXHueSvNBpO2cnACuxwaSrV9MBv7a/MFiZAw2NodNd7Eu7oHV9KBahAqShs2vZCWmvSSrlquGvqa6C1TRk5QvWdbToqsqdrk7bgPuPbLKKwK1ImiZySGXr1LddtT64XOHRPhk5waXyXSw9uhWw+F4fegJj3TbLfVH4oWWcs3sLrJqv34NzoTLeh56S8eWmMCH/nRqnIW+D8cCNoLz0tmtJ0P8D9V7ThEIkxN5FAi/oxtkWqjU2qBcrpnkvsJrOoA4/kpkPuBCCOOQdrBIpG7aNuLfq01RGKXlyfYs8ryl+KIEKATf5OqYclfdLLGIsXKFa9Z9kiMQLheA1H0AhczCzXQTugy4PekedtYMgp5N7c5PVRMG2oRQDtneTZZdHEGMmembITpW1GYVo9S3JR+TW5duaucL539KwrXrfIBdsI7/Y1mk4QaU7mqd+KsrW4qKEhJ0wRekOJeWqoqoPc7uUqxLNlstdogFXZ1NC4cgBRt51Y+NdQQGqDiAbike3NH1kMmzbbFe1BaLQ5dQihgKnHIEurbJXIQmVQ1fl+59mrSSzdRmab0AJDC0yoUlGDK0rIHV/ZtEFRXkP2Ltu+BZrc4+649RNoBIsunnU06UpD/FKc5Ia5O9jwwPrGoZChR2rMQi870nQGFe2qo5f/9JdbfLlMYYCVa8ggHdgwJOSA/UPpzVaLYaXXR+pOCLeyIZaOcBykQxihMWMWu1ssOjw1cPLntkG1JHvUyjEA7EBxeP8NLZepxn0ktd6XizHxUSC5H0oR5o9O+ExWSDyDgIMckPHEeUVlWf+YMsCU920Bfyn9Z8f3/d8EiXWskkj2NujJ7QnrMcR9zB1qumPxCHpNJR1yIv28QgwCit7yq3emZXOJphU2ODwofWvfDE33dQSpobQ8p1Qgfn/n3xrcXRDc8CJxfDQe9u7ahY8fa1QFOLmnkYAiZb5DhNkIyqkRA2Ucf9escbeLvZsrkGsH2U57QTFAiwUNp1NZRThRSXFypCffEeDO5fs2HED2tusG4aAWHZH/YiJmKJyO7Uby48d2JnpzUwUCLhrccyqxgngZ1LZyHdlA3IKXD6+nr3uvY9O35MmtCDNAkOoLyao9bD/orZXeHxqgMA1udddQki5HLYdCx+AYjdmYzsXEaBxAVfMu/8IwMTDRINLkuhki+ixe9HRTH4pCWS+bnvsyHYttrQAhmDzf18kdUuGSsagZcSDqztEoigTzcCQvVTRa98R0XYPj9zcTGAztcXbvEJG0ad81116WMx/ffTXADv41Y7D4fWxMqKff7yVgDYH5W8VpKi/wuDpDMMHSmL2xc5vEufQcyPbYi8IrDro+vc6poKijK4kw58P/9BJt72jHDWkYf8K8OrQyXAzFesejiKEKjM4jXp9KjMD5mYAiUuH/ORoDEAPd+OL30QWQ+QU2X+5u//E+i69vEUYZRpndk4KyjzsHspJz9UGUVmpErExHJ6ixVxPJaHnoTECrjouNBYalwCvvq1M0YndKCTlgl4HZzk3tQgz0knR0VzMFXRcw3j2VEH4plf7vX1iQsyglJGDUPU0BwsyxBetF8+L4iod2/9HRaE2FwPy2+2cqc3tWkg6yYLEg39YrNyw2IVYexJZ2pSZCIypNCGQbyE2Aye4jbck5QBNzpeuQMpJfjUl2HJA2OFuHQSbOq9JGQ9BbjGLCBTsnwOWi2P27SFthT/EHtNCNW7cRfqdhhHhDtAPrIrNGptLzFr4WaLNgA46m3FMqwn1XQHylQ1qdT+1/GtrdZxtRWeM3+MGmzmIwuZWBBCGep9nuv1FuBqaUyvhUrJG3EthsJvoqj/OZhRIShAB+dqIJ/x+j56KYk31fsShIzMPx0/mOKxHqBr0Gj5Gf4aLfVOSRso4ymSHYTvSyzNg8FpZbuBKu+X7MbhbasK4E5gehSIDPl9xx+3qYI6a7zxl6MdoOjLnjtuSPyzus2D15IwMYFxKbhCb26ZdP/wdeIH1Y'
TRACKS=json.loads(zlib.decompress(base64.b64decode(B64)).decode())
ROOT=pathlib.Path(__file__).resolve().parents[2]; HTML=ROOT/'youtube-playlist-player/app/src/main/assets/index.html'
def resolve(item):
 q=item['artist']+' '+item['title']
 for x in (q+' official',q):
  try:
   p=subprocess.run(['yt-dlp','--flat-playlist','--skip-download','--playlist-end','1','--print','%(id)s\t%(title)s','ytsearch1:'+x],capture_output=True,text=True,timeout=20)
   line=next((s.strip() for s in p.stdout.splitlines() if s.strip()),'')
   if line:
    parts=line.split('\t',1); vid=parts[0].strip(); title=parts[1].strip() if len(parts)>1 else ''
    if re.fullmatch(r'[A-Za-z0-9_-]{11}',vid): return vid,title
  except Exception: pass
 return None,None
flat=[(k,i,x) for k,v in TRACKS.items() for i,x in enumerate(v)]; results={k:[None]*len(v) for k,v in TRACKS.items()}; ok=0
with ThreadPoolExecutor(max_workers=10) as ex:
 fm={ex.submit(resolve,x):(k,i,x) for k,i,x in flat}
 for f in as_completed(fm):
  k,i,x=fm[f]
  try: vid,found=f.result()
  except Exception: vid,found=None,None
  ok+=bool(vid); results[k][i]={'id':vid,'url':'https://www.youtube.com/watch?v='+vid if vid else None,'label':x['title'],'artist':x['artist'],'resolvedTitle':found}
  print(f'[{k} {i+1:03d}/{len(TRACKS[k])}] '+(('OK '+vid) if vid else 'NON RESOLU')+' - '+x['artist']+' - '+x['title'],flush=True)
payload=json.dumps(results,ensure_ascii=False,separators=(',',':'))
runtime='''<script id="pme-wedding-playlists-v1">\n(function(){\nconst W=__PAYLOAD__;DEFAULT_PLAYLISTS.wedding=W.wedding;DEFAULT_PLAYLISTS.wedding_qc=W.wedding_qc;\nwindow.refreshSaved=function(){const s=$("savedSelect"),d=saved(),c=s.value;s.innerHTML='<option value="">Choisir une playlist…</option>';[["default:global","🌎 Sélection originale",DEFAULT_PLAYLISTS.global],["default:quebec","⚜️ Québec 2000–2026",DEFAULT_PLAYLISTS.quebec],["default:wedding","💍 Mariage — Top 100",DEFAULT_PLAYLISTS.wedding],["default:wedding_qc","⚜️💍 Mariage québécois — 20 titres",DEFAULT_PLAYLISTS.wedding_qc]].forEach(([v,n,l])=>{const o=document.createElement("option");o.value=v;o.textContent=n+" ("+l.length+")";s.appendChild(o)});Object.keys(d).sort().forEach(k=>{const o=document.createElement("option");o.value="user:"+k;o.textContent="💾 "+k+" ("+d[k].length+")";s.appendChild(o)});if([...s.options].some(o=>o.value===c))s.value=c};\nwindow.loadSelected=function(){const v=$("savedSelect").value,d=saved();if(!v)return;const defs={"default:global":["Sélection originale",DEFAULT_PLAYLISTS.global],"default:quebec":["Québec 2000–2026",DEFAULT_PLAYLISTS.quebec],"default:wedding":["Mariage — Top 100",DEFAULT_PLAYLISTS.wedding],"default:wedding_qc":["Mariage québécois — 20 titres",DEFAULT_PLAYLISTS.wedding_qc]};if(defs[v]){tracks=JSON.parse(JSON.stringify(defs[v][1]));$("playlistName").value=defs[v][0]}else if(v.startsWith("user:")){const n=v.slice(5);if(!d[n])return;tracks=JSON.parse(JSON.stringify(d[n]));$("playlistName").value=n}else return;index=0;render();if(ready&&tracks.length)loadCurrent(false)};\nrefreshSaved();\n})();\n</script>'''.replace('__PAYLOAD__',payload)
s=HTML.read_text(encoding='utf-8');s=re.sub(r'\n?<script id="pme-wedding-playlists-v1">.*?</script>\s*','\n',s,flags=re.S);s=s.replace('</body>',runtime+'\n</body>');HTML.write_text(s,encoding='utf-8')
print(f'Playlists mariage résolues: {ok}/{len(flat)}',flush=True)
if ok<110: raise SystemExit(f'Trop peu de titres mariage résolus: {ok}/{len(flat)}')
