from pathlib import Path
import os
root=Path(os.environ.get('GRADLE_DIR','source-5.10.4/PME-Quebec-5.10-Native-Wyze-Source'))
p=root/'app/src/main/java/com/pmequebec/app/MainActivity.java'
s=p.read_text(encoding='utf-8')
if 'PME_ANDROID_PERMISSIONS_6000' in s:
 print('Permissions déjà corrigées'); raise SystemExit(0)
s=s.replace('import android.content.pm.PackageManager;','import android.content.pm.PackageManager;\nimport android.content.Intent;\nimport android.net.Uri;\nimport android.webkit.ValueCallback;\nimport android.webkit.GeolocationPermissions;')
s=s.replace('private static final int REQ_CAMERA = 4104;\n    private PermissionRequest pendingCameraRequest;','private static final int REQ_CAMERA = 4104;\n    private static final int REQ_LOCATION = 4105;\n    private static final int REQ_INITIAL = 4106;\n    private static final int REQ_FILE = 4107;\n    private PermissionRequest pendingCameraRequest;\n    private GeolocationPermissions.Callback pendingGeoCallback;\n    private String pendingGeoOrigin;\n    private ValueCallback<Uri[]> pendingFileChooser;\n    // PME_ANDROID_PERMISSIONS_6000')
s=s.replace('s.setDomStorageEnabled(true);','s.setDomStorageEnabled(true);\n        s.setGeolocationEnabled(true);')
old='''            @Override public void onPermissionRequest(final PermissionRequest request) {\n                runOnUiThread(() -> handleWebPermissionRequest(request));\n            }\n        });'''
new='''            @Override public void onPermissionRequest(final PermissionRequest request) {\n                runOnUiThread(() -> handleWebPermissionRequest(request));\n            }\n            @Override public void onGeolocationPermissionsShowPrompt(String origin, GeolocationPermissions.Callback callback) {\n                runOnUiThread(() -> handleGeolocationPermission(origin, callback));\n            }\n            @Override public boolean onShowFileChooser(WebView view, ValueCallback<Uri[]> callback, FileChooserParams params) {\n                if (pendingFileChooser != null) pendingFileChooser.onReceiveValue(null);\n                pendingFileChooser = callback;\n                try {\n                    Intent intent = params != null ? params.createIntent() : new Intent(Intent.ACTION_OPEN_DOCUMENT);\n                    if (params == null) { intent.setType(\"*/*\"); intent.addCategory(Intent.CATEGORY_OPENABLE); }\n                    startActivityForResult(intent, REQ_FILE);\n                    return true;\n                } catch (Exception e) { pendingFileChooser = null; return false; }\n            }\n        });'''
if old not in s: raise SystemExit('WebChromeClient attendu introuvable')
s=s.replace(old,new,1)
s=s.replace('setContentView(webView);\n        startGo2RtcIfBundled();','setContentView(webView);\n        requestInitialPermissions();\n        startGo2RtcIfBundled();',1)
marker='''    private void handleWebPermissionRequest(PermissionRequest request) {'''
insert='''    private void requestInitialPermissions() {\n        if (android.os.Build.VERSION.SDK_INT < 23) return;\n        java.util.ArrayList<String> needed = new java.util.ArrayList<>();\n        if (checkSelfPermission(Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) needed.add(Manifest.permission.CAMERA);\n        if (checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) needed.add(Manifest.permission.ACCESS_FINE_LOCATION);\n        if (checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) needed.add(Manifest.permission.ACCESS_COARSE_LOCATION);\n        if (!needed.isEmpty()) requestPermissions(needed.toArray(new String[0]), REQ_INITIAL);\n    }\n\n    private void handleGeolocationPermission(String origin, GeolocationPermissions.Callback callback) {\n        if (android.os.Build.VERSION.SDK_INT < 23 || checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED || checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED) {\n            callback.invoke(origin, true, false);\n            return;\n        }\n        pendingGeoOrigin = origin; pendingGeoCallback = callback;\n        requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION}, REQ_LOCATION);\n    }\n\n'''+marker
s=s.replace(marker,insert,1)
oldreq='''        if (requestCode != REQ_CAMERA) return;\n\n        PermissionRequest request = pendingCameraRequest;\n        pendingCameraRequest = null;\n        if (request == null) return;\n\n        if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {\n            request.grant(new String[]{PermissionRequest.RESOURCE_VIDEO_CAPTURE});\n        } else {\n            request.deny();\n        }\n    }'''
newreq='''        if (requestCode == REQ_CAMERA) {\n            PermissionRequest request = pendingCameraRequest; pendingCameraRequest = null;\n            if (request != null) {\n                if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) request.grant(new String[]{PermissionRequest.RESOURCE_VIDEO_CAPTURE});\n                else request.deny();\n            }\n            return;\n        }\n        if (requestCode == REQ_LOCATION) {\n            boolean ok = checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED || checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED;\n            GeolocationPermissions.Callback cb = pendingGeoCallback; String origin = pendingGeoOrigin; pendingGeoCallback = null; pendingGeoOrigin = null;\n            if (cb != null) cb.invoke(origin, ok, false);\n            return;\n        }\n    }\n\n    @Override protected void onActivityResult(int requestCode, int resultCode, Intent data) {\n        super.onActivityResult(requestCode, resultCode, data);\n        if (requestCode != REQ_FILE) return;\n        ValueCallback<Uri[]> cb = pendingFileChooser; pendingFileChooser = null;\n        if (cb == null) return;\n        Uri[] result = null;\n        if (resultCode == RESULT_OK && data != null) {\n            if (data.getClipData() != null) {\n                int n=data.getClipData().getItemCount(); result=new Uri[n];\n                for(int i=0;i<n;i++) result[i]=data.getClipData().getItemAt(i).getUri();\n            } else if (data.getData()!=null) result=new Uri[]{data.getData()};\n        }\n        cb.onReceiveValue(result);\n    }'''
if oldreq not in s: raise SystemExit('Bloc permissions attendu introuvable')
s=s.replace(oldreq,newreq,1)
p.write_text(s,encoding='utf-8')
print('Permissions GPS/caméra + sélecteur de fichiers Android corrigés')
