from pathlib import Path
import os
root=Path(os.environ.get('GRADLE_DIR','source-5.10.4/PME-Quebec-5.10-Native-Wyze-Source'))
p=root/'app/src/main/assets/index.html'
s=p.read_text(encoding='utf-8')
needle="function openPage(name){let o=overlay(),b=o.querySelector('#pmeBody'),t=o.querySelector('#pmeTitle');o.classList.add('show');({management,office,commerce,agenda,messages,notifications,documents}[name]||management)(b,t)}"
if needle in s and 'window.PMEERP_OPEN=openPage' not in s:
    s=s.replace(needle,needle+'\nwindow.PMEERP_OPEN=openPage;',1)
STYLE='''\n<style id="pme-erp-mobile-fix-6100">\n#pmeBrandStrip{display:none!important}\n#pmeQuickBar,#pmeSuiteNav{display:flex!important;gap:8px!important;overflow-x:auto!important;overflow-y:hidden!important;padding:8px 12px!important;margin:0!important;background:#080b11!important;border:0!important;border-bottom:1px solid #1d2430!important;position:relative!important;z-index:8!important;scrollbar-width:none!important}\n#pmeQuickBar::-webkit-scrollbar,#pmeSuiteNav::-webkit-scrollbar{display:none!important}\n#pmeQuickBar button,#pmeSuiteNav button{flex:0 0 auto!important;width:auto!important;min-width:0!important;max-width:none!important;min-height:44px!important;padding:10px 14px!important;margin:0!important;border-radius:22px!important;background:linear-gradient(180deg,#151922,#0d1118)!important;color:#f5f7fb!important;border:1px solid #303746!important;box-shadow:none!important;font-size:14px!important;font-weight:750!important;line-height:1.15!important;white-space:nowrap!important;text-align:center!important}\n#pmeQuickBar button:active,#pmeSuiteNav button:active{background:#001F97!important;transform:scale(.98)!important}\n#pmeOverlay{background:#070a0f!important;color:#f5f7fb!important}\n#pmeOverlay .pmeHead{background:#070a0f!important;border-bottom:1px solid #202735!important}\n#pmeOverlay .pmeCard{background:linear-gradient(180deg,#121720,#0d1118)!important;color:#f5f7fb!important;border:1px solid #2b3443!important;box-shadow:0 8px 24px rgba(0,0,0,.18)!important}\n#pmeOverlay button{background:linear-gradient(180deg,#17233f,#0d1730)!important;color:#fff!important;border:1px solid #254b9f!important;border-radius:12px!important;min-height:44px!important}\n#pmeOverlay input,#pmeOverlay select,#pmeOverlay textarea{background:#0b1018!important;color:#fff!important;border:1px solid #394456!important}\n#pmeOverlay input::placeholder,#pmeOverlay textarea::placeholder{color:#8792a5!important}\n#pmeClose{background:#171b24!important;border:1px solid #394456!important}\n@media(max-width:700px){#pmeQuickBar,#pmeSuiteNav{padding-left:10px!important;padding-right:10px!important}#pmeQuickBar button,#pmeSuiteNav button{font-size:13px!important;padding:9px 12px!important;min-height:42px!important}#pmeOverlay{padding-left:10px!important;padding-right:10px!important}}\n</style>\n'''
SCRIPT='''\n<script id="pme-erp-mobile-runtime-fix-6100">\n(function(){'use strict';function bind(){document.addEventListener('click',function(ev){var btn=ev.target&&ev.target.closest?ev.target.closest('[data-pme]'):null;if(!btn)return;var page=btn.getAttribute('data-pme');if(!page)return;if(typeof window.PMEERP_OPEN==='function'){ev.preventDefault();ev.stopPropagation();try{window.PMEERP_OPEN(page)}catch(err){console.error('PME ERP navigation',err)}}},true)}function ensureUsable(){document.querySelectorAll('#pmeQuickBar button,#pmeSuiteNav button').forEach(function(b){b.disabled=false;b.removeAttribute('aria-disabled');b.style.pointerEvents='auto'})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){bind();ensureUsable()});else{bind();ensureUsable()}new MutationObserver(ensureUsable).observe(document.documentElement,{childList:true,subtree:true})})();\n</script>\n'''
if 'pme-erp-mobile-fix-6100' not in s:
    pos=s.lower().rfind('</head>')
    if pos<0: raise SystemExit('Balise head introuvable')
    s=s[:pos]+STYLE+s[pos:]
if 'pme-erp-mobile-runtime-fix-6100' not in s:
    pos=s.lower().rfind('</body>')
    if pos<0: raise SystemExit('Balise body introuvable')
    s=s[:pos]+SCRIPT+s[pos:]
p.write_text(s,encoding='utf-8')
print('Correctif ERP mobile applique')