package quebec.culture.donnees;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.text.DateFormat;import java.util.*;

public class DocumentActivity extends Activity{
 private DocumentStore.Item item; private List<List<String>> rows;
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));item=DocumentStore.find(this,getIntent().getStringExtra("id"));if(item==null){finish();return;}try{rows=DocumentStore.read(this,item);}catch(Exception e){rows=List.of();}setContentView(ui());}
 private View ui(){ScrollView s=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setBackgroundColor(Color.rgb(245,247,250));s.addView(r);applyInsets(r);Button back=secondary("← Bibliothèque");back.setOnClickListener(v->finish());r.addView(back);r.addView(text(item.name,27,Color.rgb(0,59,113),true));r.addView(text(labelSector()+" · "+DateFormat.getDateInstance(DateFormat.MEDIUM,Locale.CANADA_FRENCH).format(new Date(item.createdAt)),14,Color.DKGRAY,false));
  LinearLayout q=panel();q.addView(text("Qualité des données",18,Color.rgb(21,37,54),true));q.addView(text(item.score+" %",32,item.score>=80?Color.rgb(20,108,67):(item.score>=60?Color.rgb(154,103,0):Color.rgb(170,40,40)),true));DataBarView bar=new DataBarView(this);bar.setValues(item.score,Math.max(0,100-item.score-item.duplicates),item.duplicates);q.addView(bar,new LinearLayout.LayoutParams(-1,dp(50)));q.addView(text("Vert = propre · Orange = à vérifier · Rouge = problème détecté",12,Color.DKGRAY,false));r.addView(q,mb());
  LinearLayout k=panel();k.addView(text("Vue d’ensemble",18,Color.rgb(21,37,54),true));k.addView(text(item.rows+" fiches · "+item.columns+" colonnes\n"+item.emptyCells+" cellules vides · "+item.duplicates+" doublons\n"+item.changedCells+" corrections automatiques",16,Color.rgb(21,37,54),false));Button audit=primary("Voir la correspondance champ par champ");audit.setOnClickListener(v->{Intent i=new Intent(this,MappingActivity.class);i.putExtra("id",item.id);startActivity(i);});k.addView(audit);k.addView(text("Traçabilité : colonne d’origine → champ normalisé → champ cible → exemple avant/après → statut → justification.",12,Color.DKGRAY,false));r.addView(k,mb());
  LinearLayout useful=panel();useful.addView(text("Que dois-je vérifier?",18,Color.rgb(21,37,54),true));for(String x:usefulList())useful.addView(text("• "+x,14,Color.rgb(35,55,75),false));r.addView(useful,mb());
  LinearLayout data=panel();data.addView(text("Aperçu de mon fichier",18,Color.rgb(21,37,54),true));TextView preview=text(preview(rows,18),12,Color.rgb(35,55,75),false);preview.setTypeface(android.graphics.Typeface.MONOSPACE);preview.setTextIsSelectable(true);HorizontalScrollView hs=new HorizontalScrollView(this);hs.addView(preview);data.addView(hs);Button exp=primary("Exporter la copie nettoyée en CSV");exp.setOnClickListener(v->export());data.addView(exp);r.addView(data,mb());
  LinearLayout help=panel();help.addView(text("Comment interpréter le résultat",18,Color.rgb(21,37,54),true));help.addView(text("Un score élevé signifie que le fichier contient moins de problèmes détectés par l’application. Vérifiez toujours les champs vides, doublons, dates, lieux, identifiants et catégories avant diffusion. La correspondance sectorielle et le score sont des outils de préparation et de validation, pas une certification officielle.",14,Color.DKGRAY,false));r.addView(help);return s;}
 private void applyInsets(View v){v.setOnApplyWindowInsetsListener((view,in)->{android.graphics.Insets bars=in.getInsets(WindowInsets.Type.systemBars());view.setPadding(dp(18),dp(18)+bars.top,dp(18),dp(30)+bars.bottom);return in;});v.requestApplyInsets();}
 private String labelSector(){try{return DataNormalizer.Sector.valueOf(item.sector).label;}catch(Exception e){return item.sector;}}
 private String[] usefulList(){try{DataNormalizer.Sector s=DataNormalizer.Sector.valueOf(item.sector);String fields=String.join(", ",s.suggestedFields);switch(s){case METAMUSIQUE:return new String[]{"Champs recherchés : "+fields,"Artistes, titres, albums et genres doivent être uniformes","Vérifier langue, identifiants et dates de sortie"};case SCENE:return new String[]{"Champs recherchés : "+fields,"Uniformiser lieux, villes et disciplines","Vérifier dates de représentation et artistes"};case CINEMA:return new String[]{"Champs recherchés : "+fields,"Uniformiser réalisateurs, genres, pays et langues","Vérifier année et identifiants"};case LIVRE:return new String[]{"Champs recherchés : "+fields,"Uniformiser auteurs, éditeurs et catégories","Vérifier ISBN, langue et date de publication"};default:return new String[]{"Champs recherchés : "+fields,"Uniformiser institutions, lieux et catégories","Vérifier dates de début/fin et villes"};}}catch(Exception e){return new String[]{"Vérifier les champs essentiels","Uniformiser les valeurs","Corriger doublons et données manquantes"};}}
 private void export(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,item.name.replaceAll("(?i)\\.(csv|xlsx)$","")+"-culture-quebec.csv");startActivityForResult(i,9);}@Override protected void onActivityResult(int rc,int res,Intent d){super.onActivityResult(rc,res,d);if(rc==9&&res==RESULT_OK&&d!=null&&d.getData()!=null)try(OutputStream o=getContentResolver().openOutputStream(d.getData())){o.write(SpreadsheetReader.toCsv(rows).getBytes(StandardCharsets.UTF_8));Toast.makeText(this,"Document exporté.",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Export impossible",Toast.LENGTH_LONG).show();}}
 private String preview(List<List<String>> a,int max){StringBuilder b=new StringBuilder();for(int rr=0;rr<Math.min(a.size(),max);rr++){List<String> row=a.get(rr);for(int c=0;c<row.size();c++){if(c>0)b.append(" | ");String v=row.get(c);if(v.length()>30)v=v.substring(0,27)+"…";b.append(v);}b.append('\n');}if(a.size()>max)b.append("… ").append(a.size()-max).append(" ligne(s) de plus");return b.toString();}
 private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackgroundResource(R.drawable.panel);return p;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);return p;}private TextView text(String s,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(bold)t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);t.setLineSpacing(0,1.12f);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_primary);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(10);b.setLayoutParams(lp);return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(0,59,113));b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_secondary);return b;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}}
