package quebec.culture.donnees;

import android.content.*;
import android.database.*;
import android.database.sqlite.*;
import java.util.*;

public class IndigenousDatabase extends SQLiteOpenHelper {
    public static final String DB_NAME="autochtones_quebec.db";
    public static final int DB_VERSION=1;

    public static class Nation {
        public long id; public String name,selfName,language,communities,territory,summary,profileUrl;
    }
    public static class History {
        public long id; public int year; public String label,details,nations,sourceUrl;
    }
    public static class SourceRow {
        public long id; public String title,url,source,date,nation,summary;
    }

    public IndigenousDatabase(Context c){ super(c,DB_NAME,null,DB_VERSION); }

    @Override public void onCreate(SQLiteDatabase db){
        db.execSQL("CREATE TABLE nations(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,self_name TEXT,language TEXT,communities TEXT,territory TEXT,summary TEXT,profile_url TEXT)");
        db.execSQL("CREATE TABLE history(id INTEGER PRIMARY KEY AUTOINCREMENT,year INTEGER,label TEXT,details TEXT,nations TEXT,source_url TEXT)");
        db.execSQL("CREATE TABLE sources(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,url TEXT UNIQUE,source TEXT,date TEXT,nation TEXT,summary TEXT)");
        seedNations(db); seedHistory(db);
    }
    @Override public void onUpgrade(SQLiteDatabase db,int oldV,int newV){}

    private void seedNations(SQLiteDatabase db){
        addNation(db,"Abénaquis (Abénakis)","W8banaki / Abénaquis","Aln8ba8dwaw8gan","Odanak; Wôlinak","Centre-du-Québec et vallée du Saint-Laurent","Nation de la Confédération Wabanaki. La vannerie, la transmission de la langue et le Musée des Abénakis occupent une place importante dans la vie culturelle contemporaine.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/abenaquis");
        addNation(db,"Algonquins (Anichinabés)","Anichinabés / Anishinaabeg","Anishnabemowin","Hunter’s Point; Kebaowek; Kitcisakik; Kitigan Zibi; Lac-Rapide; Lac-Simon; Pikogan; Timiskaming; Winneway","Outaouais et Abitibi-Témiscamingue","Le territoire, la chasse, la pêche, le piégeage, la cueillette et la langue sont au cœur de nombreuses pratiques et transmissions culturelles anichinabées.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/algonquins");
        addNation(db,"Attikameks (Atikamekw)","Atikamekw Nehirowisiwok","Nehirowimowin","Manawan; Wemotaci; Opitciwan","Haute-Mauricie et nord de Lanaudière","La langue atikamekw demeure très vivante. Les savoirs liés au territoire, aux six saisons et aux activités traditionnelles font partie intégrante de la culture contemporaine.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/attikameks");
        addNation(db,"Cris","Eeyou / Eenou","langues cries","Chisasibi; Eastmain; Mistissini; Nemaska; Oujé-Bougoumou; Waskaganish; Waswanipi; Wemindji; Whapmagoostui","Eeyou Istchee, Baie-James","La nation crie possède des institutions politiques, éducatives, sanitaires et culturelles propres. La CBJNQ de 1975 et la Paix des Braves de 2002 ont profondément structuré ses relations modernes avec le Québec.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/cris");
        addNation(db,"Wendat","Huron-Wendat","Wendat","Wendake","Région de Québec, avec territoire ancestral beaucoup plus vaste","La nation huronne-wendat maintient une vie culturelle dynamique à Wendake, autour de la langue, de l’histoire, des arts, du patrimoine et des institutions de la nation.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/hurons-wendats");
        addNation(db,"Innus","Innu","Innu Aimun","Essipit; Mashteuiatsh; Pessamit; Uashat mak Mani-utenam; Ekuanitshit; Nutashkuan; Unamen Shipu; Pakuashipi; Matimekush–Lac John","Côte-Nord, Saguenay–Lac-Saint-Jean et intérieur du Nitassinan","L’Innu Aimun, le Nitassinan, la transmission orale et les savoirs liés au territoire sont des éléments centraux de la culture innue.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/innus");
        addNation(db,"Inuit","Inuit","Inuktitut","14 villages nordiques du Nunavik","Nunavik, au nord du 55e parallèle","La culture inuit du Nunavik s’exprime notamment par l’inuktitut, les arts, les savoirs du territoire, la chasse, la sculpture, l’estampe et des institutions régionales propres.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/inuit");
        addNation(db,"Wolastoqiyik (Malécites)","Wolastoqiyik Wahsipekuk","Wolastoquey latuwewakon","Cacouna; Kataskomiq","Bas-Saint-Laurent et vallée du Wolastoq / Saint-Jean","La nation wolastoqey est liée historiquement à la Confédération Wabanaki. Son histoire au Québec comprend notamment la réserve de Viger et les communautés actuelles de Cacouna et Kataskomiq.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/malecites");
        addNation(db,"Micmacs (Mi’gmaq)","Mi’gmaq","Mi’kmawi’simk","Listuguj; Gesgapegiag; Gespeg","Gaspésie et territoire Mi’gma’gi","Les Mi’gmaq entretiennent une longue relation avec le golfe du Saint-Laurent, la pêche, les déplacements côtiers, la langue et les arts. Trois communautés sont présentes au Québec.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/micmacs");
        addNation(db,"Mohawks","Kanien’kehá:ka","Kanien’kéha","Kahnawà:ke; Kanesatake; Akwesasne (partie québécoise)","Vallée du Saint-Laurent et territoire haudenosaunee","Les Kanien’kehá:ka font partie de la Confédération haudenosaunee. Leurs communautés du Québec maintiennent des institutions, langues, traditions et expressions culturelles propres.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/mohawks");
        addNation(db,"Naskapis","Naskapi","iyuw iyimuun","Kawawachikamach","Nord-Est du Québec","La nation naskapie possède une forte continuité linguistique et culturelle. La Convention du Nord-Est québécois de 1978 a établi un régime moderne de droits et d’institutions.","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/naskapis");
    }

    private void addNation(SQLiteDatabase db,String n,String sn,String lang,String comm,String terr,String sum,String url){
        ContentValues v=new ContentValues();v.put("name",n);v.put("self_name",sn);v.put("language",lang);v.put("communities",comm);v.put("territory",terr);v.put("summary",sum);v.put("profile_url",url);db.insert("nations",null,v);
    }

    private void seedHistory(SQLiteDatabase db){
        addHistory(db,1534,"Premiers récits coloniaux français du golfe du Saint-Laurent","Jacques Cartier rencontre des peuples autochtones dans le golfe et le Saint-Laurent. Ces récits européens commencent une documentation coloniale plus continue, alors que les peuples autochtones vivent sur ces territoires depuis des millénaires.","Plusieurs nations","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits");
        addHistory(db,1603,"Alliance de Tadoussac","Des alliances politiques et militaires franco-autochtones sont conclues à Tadoussac, notamment avec des Innus, des Anichinabés et des Wolastoqiyik/Etchemins.","Innus; Anichinabés; Wolastoqiyik","https://www.thecanadianencyclopedia.ca/fr/article/tadoussac");
        addHistory(db,1649,"Dispersion wendat","Les guerres, les épidémies et les bouleversements coloniaux entraînent la dispersion de nombreuses communautés wendat. Une partie se réorganise ensuite dans la région de Québec.","Wendat","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/hurons-wendats");
        addHistory(db,1701,"Grande Paix de Montréal","La France et de nombreuses nations autochtones concluent une paix majeure à Montréal. L’entente transforme les rapports diplomatiques et militaires dans le nord-est de l’Amérique.","Plusieurs nations","https://www.canada.ca/fr/parcs-canada/nouvelles/2022/08/la-grande-paix-de-montreal-de-1701.html");
        addHistory(db,1763,"Proclamation royale","La Proclamation royale britannique de 1763 devient un texte important de l’histoire juridique des relations avec les peuples autochtones et la question des terres.","Plusieurs nations","https://www.rcaanc-cirnac.gc.ca/eng/1370355181092/1607905122267");
        addHistory(db,1827,"Réserve de Viger","Une concession foncière est créée pour les Wolastoqiyik à Viger. Les terres sont ensuite contestées et reprises, épisode important de l’histoire territoriale de la nation au Québec.","Wolastoqiyik","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/malecites");
        addHistory(db,1876,"Loi sur les Indiens","Le Canada adopte la Loi sur les Indiens, qui impose un régime colonial fédéral à de nombreuses Premières Nations. Les Inuit ne sont pas régis par cette loi.","Premières Nations","https://laws-lois.justice.gc.ca/fra/lois/i-5/");
        addHistory(db,1893,"Famines naskapies","À partir de 1893, plusieurs famines frappent durement la nation naskapie, alors fortement dépendante des migrations du caribou et affectée par les transformations économiques du Nord.","Naskapis","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/naskapis");
        addHistory(db,1900,"Pressions industrielles croissantes","Au tournant du 20e siècle, colonisation, exploitation forestière, minière et hydroélectrique modifient profondément l’accès au territoire de plusieurs nations.","Anichinabés; Atikamekw; Innus; autres","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations");
        addHistory(db,1930,"Pensionnats et politiques d’assimilation","Au 20e siècle, des enfants autochtones du Québec sont envoyés dans des pensionnats et d’autres institutions d’assimilation. Les effets intergénérationnels sont aujourd’hui documentés par de nombreux travaux et témoignages.","Plusieurs nations","https://nctr.ca/education/teaching-resources/residential-school-history/");
        addHistory(db,1953,"Relocalisations inuit vers le Haut-Arctique","Le gouvernement fédéral relocalise des familles inuit, notamment depuis Inukjuak, vers le Haut-Arctique. Ces déplacements ont eu des conséquences durables sur les familles concernées.","Inuit","https://www.canada.ca/fr/relations-couronne-autochtones-affaires-nord/nouvelles/2019/09/lexpedition-du-haut-arctique.html");
        addHistory(db,1956,"Installation naskapie près de Schefferville","Les Naskapis s’installent avec les Innus de Matimekosh près de Schefferville, après plusieurs déplacements imposés ou encouragés par les autorités et les conditions économiques.","Naskapis; Innus","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/naskapis");
        addHistory(db,1960,"Musée des Abénakis","La Société historique d’Odanak administre à partir de 1960 le Musée des Abénakis, l’une des institutions muséales autochtones majeures du Québec.","Abénaquis","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/abenaquis");
        addHistory(db,1971,"Projet hydroélectrique de la Baie-James","L’annonce du projet de la Baie-James mobilise fortement les Cris et les Inuit et mène à des contestations judiciaires et à des négociations territoriales modernes.","Cris; Inuit","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/ententes-revendications-negociations/evenements-marquants");
        addHistory(db,1975,"Convention de la Baie-James et du Nord québécois","Les Cris et les Inuit signent avec le Québec, le Canada et d’autres parties le premier grand traité moderne au Canada. Il établit des droits territoriaux, des institutions et des régimes en santé, éducation, environnement et développement.","Cris; Inuit","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/ententes-revendications-negociations/evenements-marquants");
        addHistory(db,1978,"Convention du Nord-Est québécois","Les Naskapis signent la Convention du Nord-Est québécois, qui établit un régime de droits territoriaux, de chasse, de pêche et de piégeage ainsi que des institutions propres.","Naskapis","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/ententes-revendications-negociations/evenements-marquants");
        addHistory(db,1982,"Reconnaissance constitutionnelle des droits ancestraux et issus de traités","L’article 35 de la Loi constitutionnelle de 1982 reconnaît et confirme les droits existants — ancestraux ou issus de traités — des peuples autochtones du Canada.","Toutes les nations","https://laws-lois.justice.gc.ca/fra/const/page-13.html");
        addHistory(db,1983,"Principes du Québec sur les nations autochtones","Le Conseil des ministres du Québec adopte 15 principes qui reconnaissent notamment les peuples autochtones du Québec comme des nations distinctes ayant droit à leur culture, leur langue, leurs coutumes et traditions.","Toutes les nations","https://www.quebec.ca/gouvernement/ministeres-organismes/secretariat-premieres-nations-inuit/mission-mandats");
        addHistory(db,1990,"Crise d’Oka / Kanesatake","Le conflit autour d’un projet d’agrandissement de terrain de golf sur des terres revendiquées par les Kanien’kehá:ka de Kanesatake devient un moment marquant des relations entre Autochtones, Québec et Canada.","Kanien’kehá:ka","https://www.thecanadianencyclopedia.ca/fr/article/crise-doka");
        addHistory(db,2002,"Paix des Braves et Sanarrutik","Le Québec conclut de nouvelles ententes de partenariat avec les Cris et les Inuit, axées sur le développement, les responsabilités institutionnelles et le partage de certains revenus.","Cris; Inuit","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/profil-des-nations/cris");
        addHistory(db,2008,"Commission de vérité et réconciliation","La Commission de vérité et réconciliation du Canada commence ses travaux sur le système des pensionnats.","Toutes les nations","https://nctr.ca/about/history-of-the-trc/truth-and-reconciliation-commission-of-canada/");
        addHistory(db,2015,"94 appels à l’action de la CVR","La Commission de vérité et réconciliation publie ses appels à l’action, qui touchent notamment l’éducation, la culture, les langues, la justice et la réconciliation.","Toutes les nations","https://nctr.ca/records/reports/");
        addHistory(db,2017,"Commission Viens","Le Québec met en place la Commission d’enquête sur les relations entre les Autochtones et certains services publics.","Toutes les nations","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/commission-viens");
        addHistory(db,2019,"Rapport de la Commission Viens","Le rapport final documente des problèmes de discrimination et de traitement différentiel dans certains services publics et formule de nombreux appels à l’action.","Toutes les nations","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits/commission-viens");
        addHistory(db,2020,"Décès de Joyce Echaquan et débats sur la sécurisation culturelle","Le décès de Joyce Echaquan, femme atikamekw de Manawan, suscite une mobilisation importante et relance les débats sur la discrimination et la sécurisation culturelle dans les services publics.","Atikamekw; ensemble des peuples autochtones","https://www.coroner.gouv.qc.ca/fileadmin/Enquetes_publiques/2020-06375-40_002__1__sans_signature.pdf");
        addHistory(db,2022,"Plan d’action gouvernemental 2022-2027","Le Québec met en œuvre un plan d’action sur le mieux-être social et culturel des Premières Nations et des Inuit.","Toutes les nations","https://www.quebec.ca/gouvernement/ministeres-organismes/secretariat-premieres-nations-inuit/publications");
        addHistory(db,2025,"50e anniversaire de la CBJNQ","L’année marque 50 ans depuis la signature de la Convention de la Baie-James et du Nord québécois.","Cris; Inuit","https://www.canada.ca/fr/patrimoine-canadien/services/anniversaires-importance/2025.html");
        addHistory(db,2026,"Section vivante et données mises à jour","Cette base locale est complétée par des recherches en direct dans Données Québec et le moteur culturel afin d’ajouter des résultats récents liés aux 11 nations.","Toutes les nations","https://www.quebec.ca/gouvernement/portrait-quebec/premieres-nations-inuits");
    }

    private void addHistory(SQLiteDatabase db,int y,String l,String d,String n,String u){ContentValues v=new ContentValues();v.put("year",y);v.put("label",l);v.put("details",d);v.put("nations",n);v.put("source_url",u);db.insert("history",null,v);}

    public List<Nation> nations(){List<Nation> out=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT * FROM nations ORDER BY name",null);while(c.moveToNext()){Nation n=new Nation();n.id=c.getLong(c.getColumnIndexOrThrow("id"));n.name=c.getString(c.getColumnIndexOrThrow("name"));n.selfName=c.getString(c.getColumnIndexOrThrow("self_name"));n.language=c.getString(c.getColumnIndexOrThrow("language"));n.communities=c.getString(c.getColumnIndexOrThrow("communities"));n.territory=c.getString(c.getColumnIndexOrThrow("territory"));n.summary=c.getString(c.getColumnIndexOrThrow("summary"));n.profileUrl=c.getString(c.getColumnIndexOrThrow("profile_url"));out.add(n);}c.close();return out;}
    public List<History> history(){List<History> out=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT * FROM history ORDER BY year",null);while(c.moveToNext()){History h=new History();h.id=c.getLong(c.getColumnIndexOrThrow("id"));h.year=c.getInt(c.getColumnIndexOrThrow("year"));h.label=c.getString(c.getColumnIndexOrThrow("label"));h.details=c.getString(c.getColumnIndexOrThrow("details"));h.nations=c.getString(c.getColumnIndexOrThrow("nations"));h.sourceUrl=c.getString(c.getColumnIndexOrThrow("source_url"));out.add(h);}c.close();return out;}
    public void upsertSource(String title,String url,String source,String date,String nation,String summary){ContentValues v=new ContentValues();v.put("title",title);v.put("url",url);v.put("source",source);v.put("date",date);v.put("nation",nation);v.put("summary",summary);getWritableDatabase().insertWithOnConflict("sources",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    public List<SourceRow> searchSources(String q){List<SourceRow> out=new ArrayList<>();String like="%"+(q==null?"":q)+"%";Cursor c=getReadableDatabase().rawQuery("SELECT * FROM sources WHERE title LIKE ? OR summary LIKE ? OR nation LIKE ? ORDER BY date DESC,title ASC LIMIT 200",new String[]{like,like,like});while(c.moveToNext()){SourceRow r=new SourceRow();r.id=c.getLong(c.getColumnIndexOrThrow("id"));r.title=c.getString(c.getColumnIndexOrThrow("title"));r.url=c.getString(c.getColumnIndexOrThrow("url"));r.source=c.getString(c.getColumnIndexOrThrow("source"));r.date=c.getString(c.getColumnIndexOrThrow("date"));r.nation=c.getString(c.getColumnIndexOrThrow("nation"));r.summary=c.getString(c.getColumnIndexOrThrow("summary"));out.add(r);}c.close();return out;}
}
