package quebec.culture.donnees;

import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 private static final int OPEN_FILE=1001; private Spinner sector;
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));setContentView(build());}
 @Override protected void onResume(){super.onResume();if(sector!=null)setContentView(build());}
 private View build(){ScrollView s=new ScrollView(this);s.setFillViewport(true);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setBackgroundColor(Color.rgb(245,247,250));s.addView(r,new ScrollView.LayoutParams(-1,-1));applyInsets(r);
  r.addView(text("Culture du Québec",30,Color.rgb(0,59,113),true));r.addView(text("Données culturelles publiques + outils de normalisation",15,Color.rgb(35,55,75),false),mb());

  LinearLayout std=panel();std.addView(text("Centre de standardisation des données",22,Color.rgb(21,37,54),true));std.addView(text("Le cœur du projet : mettre à niveau une base de données culturelle selon MétaMusique, Arts de la scène, Cinéma, Livre ou Exposition muséale. Suivez les mesures de qualité, le plan de gestion, l’échéancier et les preuves nécessaires à une mise à niveau documentée.",14,Color.rgb(35,55,75),false));Button stdB=primary("✓ Ouvrir le Centre de standardisation");stdB.setOnClickListener(v->startActivity(new Intent(this,StandardizationCenterActivity.class)));std.addView(stdB);std.addView(text("La carte, la recherche et la vitrine culturelle démontrent ensuite les retombées de données mieux structurées et découvrables.",13,Color.rgb(20,108,67),false));r.addView(std,mb());

  LinearLayout indigenous=panel();indigenous.addView(text("Vitrine des 11 nations autochtones",21,Color.rgb(21,37,54),true));indigenous.addView(text("Une section dédiée de l’application regroupe les 10 Premières Nations et la nation inuit du Québec : profils des nations, langues, communautés, chronologie 1534-aujourd’hui et base de données autochtone en direct.",14,Color.rgb(35,55,75),false));Button indigenousB=primary("◈ Découvrir les 11 nations");indigenousB.setOnClickListener(v->startActivity(new Intent(this,IndigenousActivity.class)));indigenous.addView(indigenousB);indigenous.addView(text("Cette vitrine est conçue pour demeurer distincte, visible et enrichie par des sources officielles et des recherches culturelles dédiées.",13,Color.rgb(20,108,67),false));r.addView(indigenous,mb());

  LinearLayout live=panel();live.addView(text("Voir les listes directement dans l’application",20,Color.rgb(21,37,54),true));live.addView(text("Vous n’avez rien à aller chercher manuellement. L’application peut maintenant consulter les données culturelles publiques du Québec par API et les afficher sous forme de fiches.",15,Color.rgb(35,55,75),false));Button explore=primary("Explorer les données culturelles en direct");explore.setOnClickListener(v->startActivity(new Intent(this,LiveDataActivity.class)));live.addView(explore);live.addView(text("Sources intégrées : événements culturels du Québec, culture/arts/patrimoine, événements publics de Montréal et recherche dans les jeux culturels de Données Québec.",13,Color.rgb(20,108,67),false));r.addView(live,mb());

  LinearLayout searchP=panel();searchP.addView(text("Rechercher dans la culture québécoise",20,Color.rgb(21,37,54),true));searchP.addView(text("Cherchez un artiste, organisme, musée, programme, subvention, événement, film, livre ou sujet culturel. Le moteur combine des données officielles et des résultats Web, avec tri par pertinence ou par date.",14,Color.rgb(35,55,75),false));Button searchB=primary("🔎 Ouvrir le moteur de recherche culturel");searchB.setOnClickListener(v->startActivity(new Intent(this,SearchActivity.class)));searchP.addView(searchB);r.addView(searchP,mb());

  LinearLayout intro=panel();intro.addView(text("Deux façons d’utiliser l’application",20,Color.rgb(21,37,54),true));intro.addView(text("1. STANDARDISER : importer votre propre catalogue, choisir une norme reconnue, diagnostiquer et normaliser les données, puis documenter la mise à niveau.\n\n2. EXPLORER : consulter des données publiques et voir comment des contenus culturels structurés peuvent être rendus plus découvrables.",15,Color.rgb(35,55,75),false));r.addView(intro,mb());

  LinearLayout how=panel();how.addView(text("Comment l’utiliser",20,Color.rgb(21,37,54),true));how.addView(text("Pour une mise à niveau : ouvrez d’abord le Centre de standardisation, choisissez une norme et remplissez le plan de gestion. Importez ensuite votre CSV/Excel et ouvrez sa fiche d’analyse.\n\nPour les contenus autochtones : ouvrez « Découvrir les 11 nations », choisissez une nation, parcourez la chronologie ou lancez une recherche dédiée.\n\nPour voir des données : touchez « Explorer les données culturelles en direct ».\n\nPour chercher partout : ouvrez le moteur de recherche culturel. Vert = bon, orange = à vérifier, rouge = problème.",15,Color.rgb(35,55,75),false));r.addView(how,mb());

  LinearLayout guides=panel();guides.addView(text("Guides et champs par secteur",20,Color.rgb(21,37,54),true));guides.addView(text("Ces cinq guides correspondent aux profils de travail intégrés dans l’application pour préparer les données selon les secteurs reconnus.",14,Color.DKGRAY,false));String[][] gs={{"🎵  Musique — MétaMusique","METAMUSIQUE"},{"🎭  Arts de la scène","SCENE"},{"🎬  Cinéma","CINEMA"},{"📚  Livre — éditeurs","LIVRE"},{"🏛  Musées et expositions","MUSEE"}};for(String[] g:gs){Button b=secondary(g[0]+"   ›");b.setOnClickListener(v->guide(g[1]));guides.addView(b);}r.addView(guides,mb());

  List<DocumentStore.Item> docs=DocumentStore.list(this);int total=0,errors=0,score=0;for(DocumentStore.Item x:docs){total+=x.rows;errors+=x.emptyCells+x.duplicates;score+=x.score;}
  LinearLayout dash=panel();dash.addView(text("Mes données",20,Color.rgb(21,37,54),true));dash.addView(text(docs.size()+" document(s) · "+total+" fiche(s)\nQualité moyenne : "+(docs.isEmpty()?"—":(score/docs.size())+" %")+" · "+errors+" élément(s) à vérifier",15,Color.rgb(21,37,54),false));DataBarView bar=new DataBarView(this);bar.setValues(docs.isEmpty()?100:Math.max(0,score/docs.size()),docs.isEmpty()?0:Math.max(0,100-score/docs.size()),Math.min(20,errors));dash.addView(bar,new LinearLayout.LayoutParams(-1,dp(44)));r.addView(dash,mb());

  LinearLayout importP=panel();importP.addView(text("Importer mon propre catalogue",20,Color.rgb(21,37,54),true));importP.addView(text("Choisissez la norme de travail correspondant à votre projet, puis importez votre base CSV ou Excel.",14,Color.DKGRAY,false));sector=new Spinner(this);sector.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,DataNormalizer.Sector.values()));importP.addView(sector,new LinearLayout.LayoutParams(-1,dp(54)));Button imp=primary("Choisir mon fichier CSV ou Excel");imp.setOnClickListener(v->open());importP.addView(imp);r.addView(importP,mb());

  LinearLayout library=panel();library.addView(text("Mes documents",20,Color.rgb(21,37,54),true));if(docs.isEmpty())library.addView(text("Aucun document personnel. Cette section se remplit seulement après l’import de votre propre catalogue.",14,Color.DKGRAY,false));else for(DocumentStore.Item x:docs){Button b=secondary(x.name+"\n"+sectorLabel(x.sector)+" · "+x.rows+" fiches · qualité "+x.score+" %");b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setOnClickListener(v->{Intent i=new Intent(this,DocumentActivity.class);i.putExtra("id",x.id);startActivity(i);});library.addView(b);}r.addView(library,mb());

  LinearLayout who=panel();who.addView(text("Pour qui?",20,Color.rgb(21,37,54),true));who.addView(text("Organismes culturels, musées, festivals, diffuseurs, producteurs, éditeurs et autres organisations qui doivent structurer, améliorer, partager ou rendre découvrables leurs données culturelles québécoises.",14,Color.rgb(35,55,75),false));r.addView(who);return s;}
 private void applyInsets(View v){v.setOnApplyWindowInsetsListener((view,in)->{android.graphics.Insets bars=in.getInsets(WindowInsets.Type.systemBars());view.setPadding(dp(18),dp(18)+bars.top,dp(18),dp(30)+bars.bottom);return in;});v.requestApplyInsets();}
 private void guide(String sec){Intent i=new Intent(this,SectorGuideActivity.class);i.putExtra("sector",sec);startActivity(i);}
 private void open(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"text/csv","text/comma-separated-values","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/plain"});startActivityForResult(i,OPEN_FILE);}
 @Override protected void onActivityResult(int rc,int res,Intent data){super.onActivityResult(rc,res,data);if(rc!=OPEN_FILE||res!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();String n=name(u);try{List<List<String>> imported=SpreadsheetReader.read(getContentResolver(),u,n);DataNormalizer.Sector sec=(DataNormalizer.Sector)sector.getSelectedItem();DataNormalizer.Report report=DataNormalizer.normalize(imported,sec);DocumentStore.Item item=DocumentStore.save(this,n,sec,report);Intent i=new Intent(this,DocumentActivity.class);i.putExtra("id",item.id);startActivity(i);}catch(Exception e){new AlertDialog.Builder(this).setTitle("Import impossible").setMessage(e.getMessage()).setPositiveButton("OK",null).show();}}
 private String name(Uri u){String n="catalogue";try(Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())n=c.getString(0);}catch(Exception ignored){}return n==null?"catalogue":n;}
 private String sectorLabel(String s){try{return DataNormalizer.Sector.valueOf(s).label;}catch(Exception e){return s;}}
 private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackgroundResource(R.drawable.panel);return p;}private TextView text(String s,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(bold)t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);t.setLineSpacing(0,1.12f);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_primary);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(10);b.setLayoutParams(lp);return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(0,59,113));b.setTextSize(14);b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_secondary);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);b.setLayoutParams(lp);return b;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}}
