package quebec.culture.donnees;

import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 private static final int OPEN_FILE=1001; private Spinner sector; private TextView fileText,diag; private List<List<String>> imported; private String importedName="catalogue";
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));setContentView(build());}
 @Override protected void onResume(){super.onResume(); if(sector!=null)setContentView(build());}
 private View build(){ScrollView s=new ScrollView(this);s.setFillViewport(true);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setBackgroundColor(Color.rgb(245,247,250));s.addView(r,new ScrollView.LayoutParams(-1,-1));
  r.addView(text("Culture du Québec",30,Color.rgb(0,59,113),true));r.addView(text("Données Culture Québec · Bibliothèque et normalisation de catalogues",15,Color.rgb(35,55,75),false),mb());
  List<DocumentStore.Item> docs=DocumentStore.list(this);int total=0,errors=0,score=0;for(DocumentStore.Item x:docs){total+=x.rows;errors+=x.emptyCells+x.duplicates;score+=x.score;}
  LinearLayout dash=panel();dash.addView(text("Tableau de bord",19,Color.rgb(21,37,54),true));dash.addView(text(docs.size()+" document(s)   •   "+total+" fiche(s) culturelles\nQualité moyenne : "+(docs.isEmpty()?"—":(score/docs.size())+" %")+"   •   "+errors+" élément(s) à vérifier",16,Color.rgb(21,37,54),false));DataBarView bar=new DataBarView(this);bar.setValues(docs.isEmpty()?100:Math.max(0,score/docs.size()),docs.isEmpty()?0:Math.max(0,100-score/docs.size()),Math.min(20,errors));dash.addView(bar,new LinearLayout.LayoutParams(-1,dp(48)));r.addView(dash,mb());
  LinearLayout importP=panel();importP.addView(text("Ajouter un document",19,Color.rgb(21,37,54),true));sector=new Spinner(this);sector.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,DataNormalizer.Sector.values()));importP.addView(sector,new LinearLayout.LayoutParams(-1,dp(54)));fileText=text("CSV ou Excel (.xlsx)",14,Color.DKGRAY,false);importP.addView(fileText);Button imp=primary("Importer un document");imp.setOnClickListener(v->open());importP.addView(imp);diag=text("",13,Color.rgb(154,103,0),false);importP.addView(diag);r.addView(importP,mb());
  LinearLayout lists=panel();lists.addView(text("Listes utiles intégrées",19,Color.rgb(21,37,54),true));String[] ls={"Musique : titres, artistes, albums, genres, langues, dates, identifiants","Arts de la scène : spectacles, artistes, disciplines, lieux, villes, dates","Cinéma : titres, réalisateurs, années, genres, langues, pays, identifiants","Livre : titres, auteurs, éditeurs, ISBN, dates, langues, catégories","Musées : expositions, institutions, lieux, villes, dates de début/fin, catégories"};for(String x:ls)lists.addView(text("• "+x,14,Color.rgb(35,55,75),false));r.addView(lists,mb());
  LinearLayout library=panel();library.addView(text("Mes documents",19,Color.rgb(21,37,54),true));if(docs.isEmpty())library.addView(text("Aucun document enregistré. Importe ton premier catalogue pour créer sa page.",14,Color.DKGRAY,false));else for(DocumentStore.Item x:docs){Button b=secondary(x.name+"\n"+sectorLabel(x.sector)+" · "+x.rows+" fiches · qualité "+x.score+" %");b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setOnClickListener(v->{Intent i=new Intent(this,DocumentActivity.class);i.putExtra("id",x.id);startActivity(i);});library.addView(b);}r.addView(library,mb());
  LinearLayout info=panel();info.addView(text("Ce que l’application montre",19,Color.rgb(21,37,54),true));info.addView(text("Chaque document possède sa propre page avec un score de qualité, une barre visuelle vert/orange/rouge, le nombre de fiches et colonnes, les cellules vides, les doublons, les corrections automatiques, les listes de champs utiles et un aperçu des données.",14,Color.rgb(35,55,75),false));info.addView(text("Les fichiers sont traités et conservés localement sur l’appareil dans cette version.",14,Color.rgb(20,108,67),false));r.addView(info);return s; }
 private void open(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"text/csv","text/comma-separated-values","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/plain"});startActivityForResult(i,OPEN_FILE);} 
 @Override protected void onActivityResult(int rc,int res,Intent data){super.onActivityResult(rc,res,data);if(rc!=OPEN_FILE||res!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();importedName=name(u);try{imported=SpreadsheetReader.read(getContentResolver(),u,importedName);DataNormalizer.Sector sec=(DataNormalizer.Sector)sector.getSelectedItem();DataNormalizer.Report report=DataNormalizer.normalize(imported,sec);DocumentStore.Item item=DocumentStore.save(this,importedName,sec,report);Toast.makeText(this,"Document ajouté à la bibliothèque.",Toast.LENGTH_LONG).show();Intent i=new Intent(this,DocumentActivity.class);i.putExtra("id",item.id);startActivity(i);}catch(Exception e){new AlertDialog.Builder(this).setTitle("Import impossible").setMessage(e.getMessage()).setPositiveButton("OK",null).show();}}
 private String name(Uri u){String n="catalogue";try(Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())n=c.getString(0);}catch(Exception ignored){}return n==null?"catalogue":n;}
 private String sectorLabel(String s){try{return DataNormalizer.Sector.valueOf(s).label;}catch(Exception e){return s;}}
 private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackgroundResource(R.drawable.panel);return p;}private TextView text(String s,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(bold)t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);t.setLineSpacing(0,1.12f);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_primary);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(10);b.setLayoutParams(lp);return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(0,59,113));b.setTextSize(14);b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_secondary);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);b.setLayoutParams(lp);return b;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} }
