package quebec.culture.donnees;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MappingActivity extends Activity{
 private static final int EXPORT_AUDIT=41;private DocumentStore.Item item;private List<DataNormalizer.ColumnMapping> maps;
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));item=DocumentStore.find(this,getIntent().getStringExtra("id"));if(item==null){finish();return;}try{maps=DocumentStore.readMappings(this,item);}catch(Exception e){maps=new ArrayList<>();}setContentView(ui());}
 private View ui(){ScrollView s=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setBackgroundColor(Color.rgb(245,247,250));s.addView(r);applyInsets(r);
  Button back=secondary("← Retour au document");back.setOnClickListener(v->finish());r.addView(back);r.addView(text("Correspondance à la norme",27,Color.rgb(0,59,113),true));r.addView(text(labelSector()+" · audit champ par champ",14,Color.DKGRAY,false));
  LinearLayout intro=panel();intro.addView(text("Traçabilité des transformations",18,Color.rgb(21,37,54),true));intro.addView(text("Chaque colonne importée est reliée à un champ du profil sectoriel lorsque la correspondance est suffisamment claire. L’application conserve le nom d’origine, le nom normalisé, un exemple avant/après, le statut et la justification. Les correspondances proposées doivent être validées par une personne responsable des données.",14,Color.rgb(35,55,75),false));r.addView(intro,mb());
  if(maps.isEmpty()){LinearLayout p=panel();p.addView(text("Aucun audit détaillé disponible",18,Color.rgb(170,40,40),true));p.addView(text("Ce document provient probablement d’une version antérieure. Réimportez le fichier pour générer la correspondance champ par champ.",14,Color.DKGRAY,false));r.addView(p);return s;}
  int ok=0,validate=0,out=0;for(DataNormalizer.ColumnMapping m:maps){if("CONFORME".equals(m.status))ok++;else if("À VALIDER".equals(m.status))validate++;else out++;}
  LinearLayout sum=panel();sum.addView(text("Résumé",18,Color.rgb(21,37,54),true));sum.addView(text(ok+" conforme(s) · "+validate+" à valider · "+out+" hors profil",16,Color.rgb(21,37,54),false));Button export=primary("Exporter l’audit des champs en CSV");export.setOnClickListener(v->exportAudit());sum.addView(export);r.addView(sum,mb());
  for(DataNormalizer.ColumnMapping m:maps){LinearLayout p=panel();int c="CONFORME".equals(m.status)?Color.rgb(20,108,67):("À VALIDER".equals(m.status)?Color.rgb(154,103,0):Color.rgb(170,40,40));p.addView(text(m.status,13,c,true));p.addView(text("Colonne d’origine : "+safe(m.sourceHeader),15,Color.rgb(21,37,54),true));p.addView(text("Champ normalisé : "+safe(m.normalizedHeader)+"\nChamp cible : "+(m.targetField.isEmpty()?"Aucune correspondance":m.targetField),14,Color.rgb(35,55,75),false));p.addView(text("Exemple avant : "+sample(m.sampleBefore)+"\nValeur corrigée : "+sample(m.sampleAfter),14,Color.rgb(35,55,75),false));p.addView(text("Justification : "+safe(m.reason),13,Color.DKGRAY,false));r.addView(p,mb());}
  LinearLayout note=panel();note.addView(text("Important",18,Color.rgb(21,37,54),true));note.addView(text("Cet audit documente la mise à niveau technique et facilite la validation. Il ne constitue pas une certification officielle de conformité à une norme sectorielle.",14,Color.DKGRAY,false));r.addView(note);return s;}
 private void exportAudit(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/csv");String base=item.name==null?"catalogue":item.name.replaceAll("(?i)\\.(csv|xlsx)$","");i.putExtra(Intent.EXTRA_TITLE,base+"-audit-standardisation.csv");startActivityForResult(i,EXPORT_AUDIT);}
 @Override protected void onActivityResult(int rc,int res,Intent d){super.onActivityResult(rc,res,d);if(rc!=EXPORT_AUDIT||res!=RESULT_OK||d==null||d.getData()==null)return;try(OutputStream o=getContentResolver().openOutputStream(d.getData())){o.write(auditCsv().getBytes(StandardCharsets.UTF_8));Toast.makeText(this,"Audit exporté.",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Export impossible",Toast.LENGTH_LONG).show();}}
 private String auditCsv(){StringBuilder b=new StringBuilder();b.append("colonne_origine,champ_normalise,champ_cible,statut,exemple_avant,valeur_corrigee,justification\n");for(DataNormalizer.ColumnMapping m:maps){csv(b,m.sourceHeader);b.append(',');csv(b,m.normalizedHeader);b.append(',');csv(b,m.targetField);b.append(',');csv(b,m.status);b.append(',');csv(b,m.sampleBefore);b.append(',');csv(b,m.sampleAfter);b.append(',');csv(b,m.reason);b.append('\n');}return b.toString();}
 private void csv(StringBuilder b,String v){String s=v==null?"":v;if(s.contains(",")||s.contains("\"")||s.contains("\n")){b.append('"').append(s.replace("\"","\"\"")).append('"');}else b.append(s);}
 private String labelSector(){try{return DataNormalizer.Sector.valueOf(item.sector).label;}catch(Exception e){return item.sector;}}
 private String safe(String s){return s==null||s.isBlank()?"—":s;}private String sample(String s){if(s==null||s.isBlank())return "—";return s.length()>80?s.substring(0,77)+"…":s;}
 private void applyInsets(View v){v.setOnApplyWindowInsetsListener((view,in)->{android.graphics.Insets bars=in.getInsets(WindowInsets.Type.systemBars());view.setPadding(dp(18),dp(18)+bars.top,dp(18),dp(30)+bars.bottom);return in;});v.requestApplyInsets();}
 private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackgroundResource(R.drawable.panel);return p;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);return p;}private TextView text(String s,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(bold)t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);t.setLineSpacing(0,1.12f);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_primary);return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(0,59,113));b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_secondary);return b;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
