package quebec.culture.donnees;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;

public class ProjectTimelineActivity extends Activity{
 private SharedPreferences p; private LinearLayout root; private final String[] phases={"Inventaire et sauvegarde de la base existante","Cartographie vers la norme sectorielle","Nettoyage et normalisation","Validation humaine et contrôle qualité","Export interopérable et documentation","Données ouvertes / partage si les droits le permettent","Mesure des résultats et reddition de comptes"};
 @Override protected void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("project_timeline",MODE_PRIVATE);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));setContentView(build());}
 private View build(){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(30));root.setBackgroundColor(Color.rgb(245,247,250));s.addView(root);applyInsets(root);root.addView(text("Échéancier du projet",28,Color.rgb(0,59,113),true));root.addView(text("Plan de réalisation sur un maximum de 12 mois. Les étapes sont enregistrées localement et servent à démontrer la faisabilité du projet.",14,Color.DKGRAY,false),mb());
  for(int i=0;i<phases.length;i++){final int n=i;LinearLayout box=panel();CheckBox c=new CheckBox(this);c.setText(phases[i]);c.setTextSize(15);c.setTextColor(Color.rgb(21,37,54));c.setChecked(p.getBoolean("done"+i,false));box.addView(c);EditText months=new EditText(this);months.setHint("Mois prévus (ex. 1–2)");months.setText(p.getString("months"+i,""));box.addView(months);EditText note=new EditText(this);note.setHint("Livrable / responsable / preuve");note.setText(p.getString("note"+i,""));note.setMinLines(2);box.addView(note);c.setOnCheckedChangeListener((v,x)->p.edit().putBoolean("done"+n,x).apply());months.setOnFocusChangeListener((v,f)->{if(!f)p.edit().putString("months"+n,months.getText().toString()).apply();});note.setOnFocusChangeListener((v,f)->{if(!f)p.edit().putString("note"+n,note.getText().toString()).apply();});root.addView(box,mb());}
  Button save=new Button(this);save.setText("Enregistrer l’échéancier");save.setAllCaps(false);save.setTextColor(Color.WHITE);save.setBackgroundResource(R.drawable.button_primary);save.setOnClickListener(v->{saveAll();Toast.makeText(this,"Échéancier enregistré",Toast.LENGTH_SHORT).show();});root.addView(save);return s;}
 private void saveAll(){int child=2;for(int i=0;i<phases.length;i++){LinearLayout box=(LinearLayout)root.getChildAt(child++);CheckBox c=(CheckBox)box.getChildAt(0);EditText m=(EditText)box.getChildAt(1),n=(EditText)box.getChildAt(2);p.edit().putBoolean("done"+i,c.isChecked()).putString("months"+i,m.getText().toString()).putString("note"+i,n.getText().toString()).apply();}}
 private void applyInsets(View v){v.setOnApplyWindowInsetsListener((view,in)->{android.graphics.Insets bars=in.getInsets(WindowInsets.Type.systemBars());view.setPadding(dp(18),dp(18)+bars.top,dp(18),dp(30)+bars.bottom);return in;});v.requestApplyInsets();}private LinearLayout panel(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(14),dp(12),dp(14),dp(12));x.setBackgroundResource(R.drawable.panel);return x;}private TextView text(String s,int z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(b)t.setTypeface(android.graphics.Typeface.DEFAULT,1);return t;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(-1,-2);x.bottomMargin=dp(12);return x;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}