package quebec.culture.donnees;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;

public class RiskRegisterActivity extends Activity{
 private SharedPreferences p;private LinearLayout root;private final String[] names={"Qualité insuffisante des données sources","Retard dans la cartographie vers la norme","Manque de disponibilité de l’équipe","Dépendance à un fournisseur ou consultant","Droits/licences limitant les données ouvertes","Dépassement de budget","Perte ou corruption de données","Changement de portée du projet"};
 @Override protected void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("risk_register",MODE_PRIVATE);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));setContentView(build());}
 private View build(){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(30));root.setBackgroundColor(Color.rgb(245,247,250));s.addView(root);applyInsets(root);root.addView(text("Registre des risques",28,Color.rgb(0,59,113),true));root.addView(text("Documentez les risques, leur niveau et la mesure de mitigation prévue. Ce registre sert à appuyer la faisabilité et le suivi du projet.",14,Color.DKGRAY,false),mb());for(int i=0;i<names.length;i++){final int n=i;LinearLayout box=panel();box.addView(text(names[i],16,Color.rgb(21,37,54),true));Spinner level=new Spinner(this);String[] lv={"Faible","Moyen","Élevé"};level.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,lv));level.setSelection(p.getInt("level"+i,0));box.addView(level);EditText mitigation=new EditText(this);mitigation.setHint("Mesure de mitigation / responsable / preuve");mitigation.setText(p.getString("mit"+i,""));mitigation.setMinLines(2);box.addView(mitigation);level.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> a,View v,int pos,long id){p.edit().putInt("level"+n,pos).apply();}public void onNothingSelected(android.widget.AdapterView<?> a){}});mitigation.setOnFocusChangeListener((v,f)->{if(!f)p.edit().putString("mit"+n,mitigation.getText().toString()).apply();});root.addView(box,mb());}Button save=new Button(this);save.setText("Enregistrer le registre");save.setAllCaps(false);save.setTextColor(Color.WHITE);save.setBackgroundResource(R.drawable.button_primary);save.setOnClickListener(v->{saveAll();Toast.makeText(this,"Registre des risques enregistré",Toast.LENGTH_SHORT).show();});root.addView(save);return s;}
 private void saveAll(){int child=2;for(int i=0;i<names.length;i++){LinearLayout box=(LinearLayout)root.getChildAt(child++);Spinner sp=(Spinner)box.getChildAt(1);EditText e=(EditText)box.getChildAt(2);p.edit().putInt("level"+i,sp.getSelectedItemPosition()).putString("mit"+i,e.getText().toString()).apply();}}
 private void applyInsets(View v){v.setOnApplyWindowInsetsListener((q,in)->{android.graphics.Insets b=in.getInsets(WindowInsets.Type.systemBars());q.setPadding(dp(18),dp(18)+b.top,dp(18),dp(30)+b.bottom);return in;});v.requestApplyInsets();}private LinearLayout panel(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(14),dp(12),dp(14),dp(12));x.setBackgroundResource(R.drawable.panel);return x;}private TextView text(String s,int z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(b)t.setTypeface(android.graphics.Typeface.DEFAULT,1);return t;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(-1,-2);x.bottomMargin=dp(12);return x;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}