package quebec.culture.donnees;

import android.app.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import org.xmlpull.v1.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.*;import java.util.*;

public class SearchActivity extends Activity{
 private static final int BLUE=Color.rgb(0,59,113),TEXT=Color.rgb(28,45,62);private EditText query;private Spinner scope,sort;private LinearLayout results;private TextView status;private final Handler ui=new Handler(Looper.getMainLooper());
 static class R{String title,url,desc,source,date;int score;R(String t,String u,String d,String s,String dt,int sc){title=t;url=u;desc=d;source=s;date=dt;score=sc;}}
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));setContentView(build());}
 private View build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(34));root.setBackgroundColor(Color.rgb(245,247,250));sv.addView(root);applyInsets(root);Button back=secondary("← Retour");back.setOnClickListener(v->finish());root.addView(back);root.addView(text("Recherche culturelle Québec",28,BLUE,true));root.addView(text("Recherche fédérée dans les données publiques et sur le Web culturel québécois. Les résultats officiels sont identifiés séparément des autres résultats Web.",14,TEXT,false),mb());
  LinearLayout p=panel();query=new EditText(this);query.setHint("Ex. théâtre, subvention, musée, cinéma, musique…");query.setSingleLine(true);p.addView(query,new LinearLayout.LayoutParams(-1,dp(56)));scope=new Spinner(this);scope.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Toutes les sources","Ministère de la Culture","Données Québec","Web culturel québécois"}));p.addView(scope,new LinearLayout.LayoutParams(-1,dp(54)));sort=new Spinner(this);sort.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Pertinence","Plus récent"}));p.addView(sort,new LinearLayout.LayoutParams(-1,dp(54)));Button go=primary("Rechercher");go.setOnClickListener(v->search());p.addView(go);Button web=secondary("Ouvrir aussi une recherche Web complète");web.setOnClickListener(v->openWeb());p.addView(web);root.addView(p,mb());status=text("Entrez un terme de recherche.",14,Color.DKGRAY,false);root.addView(status,mb());results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);root.addView(results);return sv;}
 private void search(){String q=query.getText().toString().trim();if(q.isEmpty()){Toast.makeText(this,"Entrez un terme.",Toast.LENGTH_SHORT).show();return;}status.setText("Recherche en cours…");results.removeAllViews();new Thread(()->{List<R> all=new ArrayList<>();String sc=String.valueOf(scope.getSelectedItem());try{if(!sc.equals("Ministère de la Culture")&&!sc.equals("Web culturel québécois"))all.addAll(searchCkan(q));}catch(Exception ignored){}try{if(!sc.equals("Données Québec"))all.addAll(searchWeb(q,sc));}catch(Exception ignored){}sort(all);ui.post(()->show(all));}).start();}
 private List<R> searchCkan(String q)throws Exception{List<R> out=new ArrayList<>();String order=sort.getSelectedItemPosition()==1?"metadata_modified desc":"score desc, metadata_modified desc";String u="https://www.donneesquebec.ca/recherche/api/3/action/package_search?q="+URLEncoder.encode(q,"UTF-8")+"&rows=40&sort="+URLEncoder.encode(order,"UTF-8");JSONArray a=new JSONObject(get(u)).getJSONObject("result").optJSONArray("results");if(a!=null)for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p==null)continue;String t=p.optString("title",p.optString("name"));String d=strip(p.optString("notes",""));String dt=p.optString("metadata_modified","");String url="https://www.donneesquebec.ca/recherche/dataset/"+p.optString("name");String org="Données Québec";try{org=p.getJSONObject("organization").optString("title",org);}catch(Exception ignored){}out.add(new R(t,url,d,"OFFICIEL · "+org,dt,100-i));}return out;}
 private List<R> searchWeb(String q,String sc)throws Exception{List<R> out=new ArrayList<>();String qq=q; if(sc.equals("Ministère de la Culture"))qq=q+" site:quebec.ca/gouvernement/ministeres-organismes/culture-communications";else if(sc.equals("Web culturel québécois"))qq=q+" Québec culture arts patrimoine musée théâtre cinéma musique livre";else qq=q+" Québec culture";String u="https://www.bing.com/search?format=rss&q="+URLEncoder.encode(qq,"UTF-8");XmlPullParser x=XmlPullParserFactory.newInstance().newPullParser();x.setInput(new InputStreamReader(new URL(u).openStream(),StandardCharsets.UTF_8));String tag="",title="",link="",desc="",date="";int n=0;for(int e=x.getEventType();e!=XmlPullParser.END_DOCUMENT;e=x.next()){if(e==XmlPullParser.START_TAG){tag=x.getName();if("item".equals(tag)){title=link=desc=date="";}}else if(e==XmlPullParser.TEXT){String v=x.getText();if("title".equals(tag))title+=v;else if("link".equals(tag))link+=v;else if("description".equals(tag))desc+=v;else if("pubDate".equals(tag))date+=v;}else if(e==XmlPullParser.END_TAG&&"item".equals(x.getName())){String source=isOfficial(link)?"OFFICIEL · Web gouvernemental/culturel":"WEB · Source externe";out.add(new R(strip(title),link,strip(desc),source,date,70-n));n++;}}return out;}
 private boolean isOfficial(String u){String s=u.toLowerCase(Locale.ROOT);return s.contains("quebec.ca")||s.contains("gouv.qc.ca")||s.contains("donneesquebec.ca")||s.contains("statistique.quebec.ca")||s.contains("calq.gouv.qc.ca")||s.contains("sodec.gouv.qc.ca")||s.contains("banq.qc.ca");}
 private void sort(List<R>a){if(sort.getSelectedItemPosition()==1)Collections.sort(a,(x,y)->parseDate(y.date).compareTo(parseDate(x.date)));else Collections.sort(a,(x,y)->Integer.compare(y.score,x.score));}
 private Date parseDate(String s){if(s==null||s.isEmpty())return new Date(0);String[] f={"yyyy-MM-dd'T'HH:mm:ss","yyyy-MM-dd","EEE, dd MMM yyyy HH:mm:ss z"};for(String p:f)try{return new SimpleDateFormat(p,Locale.ENGLISH).parse(s);}catch(Exception ignored){}return new Date(0);}
 private void show(List<R>a){results.removeAllViews();status.setText(a.size()+" résultat(s) · tri : "+sort.getSelectedItem()+".");if(a.isEmpty()){results.addView(text("Aucun résultat trouvé. Essayez un terme plus général.",14,Color.DKGRAY,false));return;}for(R r:a){LinearLayout c=panel();c.addView(text(r.title,18,TEXT,true));c.addView(text(r.source,12,r.source.startsWith("OFFICIEL")?Color.rgb(20,108,67):Color.DKGRAY,true));if(r.date!=null&&!r.date.isEmpty())c.addView(text("📅 "+friendlyDate(r.date),13,TEXT,false));if(r.desc!=null&&!r.desc.isEmpty())c.addView(text(shorten(r.desc,260),13,Color.DKGRAY,false));Button o=primarySmall("OUVRIR LA SOURCE");o.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(r.url)));}catch(Exception ignored){}});c.addView(o);results.addView(c,mb());}}
 private void openWeb(){String q=query.getText().toString().trim();if(q.isEmpty())q="culture Québec";String qq=q+" Québec culture";try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?q="+URLEncoder.encode(qq,"UTF-8"))));}catch(Exception ignored){}}
 private String get(String address)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(address).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(18000);c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","CultureDuQuebec/1.6");BufferedReader b=new BufferedReader(new InputStreamReader(c.getInputStream(),StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();String l;while((l=b.readLine())!=null)s.append(l);b.close();c.disconnect();return s.toString();}
 private String strip(String s){return s==null?"":s.replaceAll("<[^>]*>"," ").replace("&nbsp;"," ").replaceAll("\\s+"," ").trim();}private String shorten(String s,int m){return s.length()<=m?s:s.substring(0,m-1)+"…";}private String friendlyDate(String s){if(s==null||s.isEmpty())return "date non indiquée";if(s.length()>=10&&s.charAt(4)=='-'&&s.charAt(7)=='-')return s.substring(8,10)+"/"+s.substring(5,7)+"/"+s.substring(0,4);return s;}
 private void applyInsets(View v){v.setOnApplyWindowInsetsListener((view,in)->{android.graphics.Insets b=in.getInsets(WindowInsets.Type.systemBars());view.setPadding(dp(18),dp(18)+b.top,dp(18),dp(34)+b.bottom);return in;});v.requestApplyInsets();}private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackgroundResource(R.drawable.panel);return p;}private TextView text(String s,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(bold)t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);t.setLineSpacing(0,1.12f);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_primary);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(9);b.setLayoutParams(lp);return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(BLUE);b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_secondary);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(8);b.setLayoutParams(lp);return b;}private Button primarySmall(String s){Button b=primary(s);b.setTextSize(12);return b;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}}
