package quebec.culture.donnees;

import android.app.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;

public class SectorGuideActivity extends Activity{
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));setContentView(ui());}
 private View ui(){String key=getIntent().getStringExtra("sector");DataNormalizer.Sector s;try{s=DataNormalizer.Sector.valueOf(key);}catch(Exception e){s=DataNormalizer.Sector.METAMUSIQUE;}ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(18),dp(18),dp(30));r.setBackgroundColor(Color.rgb(245,247,250));sv.addView(r);applyInsets(r);Button back=secondary("← Retour");back.setOnClickListener(v->finish());r.addView(back);r.addView(text(s.label,28,Color.rgb(0,59,113),true));r.addView(text("Guide pour comprendre la liste de données",15,Color.DKGRAY,false),mb());
  LinearLayout meaning=panel();meaning.addView(text("Qu’est-ce que cette liste?",20,Color.rgb(21,37,54),true));meaning.addView(text("Ce n’est pas une liste de contenus à télécharger. C’est une liste de CHAMPS : les colonnes/informations utiles à retrouver dans votre catalogue. Elle sert de repère lorsque vous préparez ou vérifiez votre fichier.",15,Color.rgb(35,55,75),false));r.addView(meaning,mb());
  LinearLayout fields=panel();fields.addView(text("Champs à rechercher dans votre fichier",20,Color.rgb(21,37,54),true));for(String f:s.suggestedFields)fields.addView(text("✓  "+pretty(f),16,Color.rgb(21,37,54),false));r.addView(fields,mb());
  LinearLayout interpret=panel();interpret.addView(text("Comment les interpréter",20,Color.rgb(21,37,54),true));interpret.addView(text(explain(s),15,Color.rgb(35,55,75),false));r.addView(interpret,mb());
  LinearLayout example=panel();example.addView(text("Exemple concret",20,Color.rgb(21,37,54),true));example.addView(text(example(s),14,Color.rgb(35,55,75),false));r.addView(example,mb());
  LinearLayout colors=panel();colors.addView(text("Après l’import",20,Color.rgb(21,37,54),true));colors.addView(text("🟢 Vert : donnée propre selon les contrôles de l’application.\n🟠 Orange : donnée à vérifier ou information manquante.\n🔴 Rouge : problème détecté, par exemple un doublon.\n\nLe score est un indicateur de qualité interne, pas une certification officielle.",15,Color.rgb(35,55,75),false));r.addView(colors);return sv;}
 private String explain(DataNormalizer.Sector s){switch(s){case METAMUSIQUE:return "Une ligne représente normalement une œuvre ou un enregistrement. Les colonnes décrivent le titre, l’artiste, l’album, le genre, la langue, la date et les identifiants disponibles.";case SCENE:return "Une ligne peut représenter un spectacle ou une représentation. Vérifiez surtout le titre, les artistes, la discipline, le lieu, la ville et la date.";case CINEMA:return "Une ligne représente un film ou une œuvre audiovisuelle. Les champs servent à distinguer clairement titre, réalisation, année, genre, langue, pays et identifiant.";case LIVRE:return "Une ligne représente généralement un livre ou une édition. L’ISBN est particulièrement utile pour identifier une édition; auteur, éditeur, langue, catégorie et date complètent la description.";default:return "Une ligne représente une exposition ou une fiche d’exposition. Institution, lieu, ville, catégories et dates permettent de décrire où et quand elle est présentée.";}}
 private String example(DataNormalizer.Sector s){switch(s){case METAMUSIQUE:return "Titre : Exemple de chanson\nArtiste : Artiste exemple\nGenre : Pop\nLangue : fr\nDate : 2026-09-13";case SCENE:return "Spectacle : Exemple sur scène\nArtiste : Compagnie exemple\nDiscipline : Théâtre\nVille : Montréal\nDate : 2026-09-13";case CINEMA:return "Titre : Film exemple\nRéalisation : Nom exemple\nAnnée : 2026\nLangue : fr\nPays : Canada";case LIVRE:return "Titre : Livre exemple\nAuteur : Nom exemple\nÉditeur : Éditeur exemple\nISBN : 9780000000000\nLangue : fr";default:return "Exposition : Exemple\nInstitution : Musée exemple\nVille : Québec\nDébut : 2026-09-13\nFin : 2027-01-10";}}
 private String pretty(String x){return x.replace('_',' ');}
 private void applyInsets(View v){v.setOnApplyWindowInsetsListener((view,in)->{android.graphics.Insets bars=in.getInsets(WindowInsets.Type.systemBars());view.setPadding(dp(18),dp(18)+bars.top,dp(18),dp(30)+bars.bottom);return in;});v.requestApplyInsets();}
 private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackgroundResource(R.drawable.panel);return p;}private TextView text(String s,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);if(bold)t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);t.setLineSpacing(0,1.12f);return t;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.rgb(0,59,113));b.setAllCaps(false);b.setBackgroundResource(R.drawable.button_secondary);return b;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}}
