package quebec.culture.donnees;
import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;import java.util.*;
public class StandardizationCenterActivity extends Activity{
 private LinearLayout root;private SharedPreferences prefs;private Spinner standard;private EditText organisation,responsable,sources,quality,sharing,retention,target,schedule;
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));prefs=getSharedPreferences("standardisation_plan",MODE_PRIVATE);setContentView(build());}
 private View build(){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(30));root.setBackgroundColor(Color.rgb(245,247,250));s.addView(root);applyInsets(root);root.addView(text("Centre de standardisation",29,Color.rgb(0,59,113),true));root.addView(text("Mise à niveau concrète des bases de données culturelles selon les 5 normes sectorielles reconnues par le ministère de la Culture et des Communications.",15,Color.rgb(35,55,75),false),mb());addNorms();addMetrics();addWorkflow();addPlan();addEligibility();addReporting();return s;}
 private void addNorms(){LinearLayout p=panel();p.addView(text("1 · Norme sectorielle",21,Color.rgb(21,37,54),true));String[] a={"MétaMusique","Arts de la scène","Cinéma","Livre — pour les éditeurs","Exposition dans un contexte muséal"};standard=new Spinner(this);standard.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));standard.setSelection(Math.max(0,Math.min(prefs.getInt("standard",0),4)));p.addView(standard);Button g=secondary("Voir le guide de la norme");g.setOnClickListener(v->{String[] c={"METAMUSIQUE","SCENE","CINEMA","LIVRE","MUSEE"};Intent i=new Intent(this,SectorGuideActivity.class);i.putExtra("sector",c[standard.getSelectedItemPosition()]);startActivity(i);});p.addView(g);root.addView(p,mb());}
 private void addMetrics(){List<DocumentStore.Item>d=DocumentStore.list(this);int rows=0,empty=0,dup=0,score=0;for(DocumentStore.Item x:d){rows+=x.rows;empty+=x.emptyCells;dup+=x.duplicates;score+=x.score;}int avg=d.isEmpty()?0:score/d.size();LinearLayout p=panel();p.addView(text("2 · Mesures et preuves",21,Color.rgb(21,37,54),true));p.addView(text("Catalogues : "+d.size()+"\nFiches : "+rows+"\nQualité moyenne : "+(d.isEmpty()?"—":avg+" %")+"\nCellules vides : "+empty+"\nDoublons : "+dup,15,Color.DKGRAY,false));root.addView(p,mb());}
 private void addWorkflow(){LinearLayout p=panel();p.addView(text("3 · Parcours de mise à niveau",21,Color.rgb(21,37,54),true));p.addView(text("IMPORTER → CARTOGRAPHIER → DIAGNOSTIQUER → NORMALISER → VALIDER → EXPORTER → PARTAGER → MESURER",14,Color.rgb(0,59,113),true));Button t=primary("Planifier l’échéancier sur 12 mois");t.setOnClickListener(v->startActivity(new Intent(this,ProjectTimelineActivity.class)));p.addView(t);root.addView(p,mb());}
 private void addPlan(){LinearLayout p=panel();p.addView(text("4 · Plan de gestion des données",21,Color.rgb(21,37,54),true));organisation=field(p,"Organisation","organisation");responsable=field(p,"Responsable des données","responsable");sources=field(p,"Sources et provenance","sources");quality=field(p,"Contrôle de qualité","quality");sharing=field(p,"Partage / données ouvertes","sharing");retention=field(p,"Sauvegardes, conservation et versions","retention");target=field(p,"Cible mesurable","target");schedule=field(p,"Échéancier global (12 mois maximum)","schedule");Button b=primary("Enregistrer le plan");b.setOnClickListener(v->savePlan());p.addView(b);root.addView(p,mb());}
 private void addEligibility(){LinearLayout p=panel();p.addView(text("5 · Préparation du dossier",21,Color.rgb(21,37,54),true));Button b=primary("Calculateur budgétaire");b.setOnClickListener(v->startActivity(new Intent(this,BudgetActivity.class)));p.addView(b);Button c=secondary("Liste de contrôle du dossier");c.setOnClickListener(v->startActivity(new Intent(this,ApplicationChecklistActivity.class)));p.addView(c);p.addView(text("Les gabarits et décisions du Ministère demeurent la référence officielle.",12,Color.DKGRAY,false));root.addView(p,mb());}
 private void addReporting(){LinearLayout p=panel();p.addView(text("6 · Résultats et reddition de comptes",21,Color.rgb(21,37,54),true));Button e=primary("Preuves et résultats");e.setOnClickListener(v->startActivity(new Intent(this,ProjectEvidenceActivity.class)));p.addView(e);Button sh=secondary("Partager le résumé du projet");sh.setOnClickListener(v->shareSummary());p.addView(sh);root.addView(p,mb());}
 private EditText field(LinearLayout p,String l,String k){p.addView(text(l,13,Color.rgb(21,37,54),true));EditText e=new EditText(this);e.setText(prefs.getString(k,""));e.setHint(l);e.setMinLines(2);e.setGravity(Gravity.TOP|Gravity.START);e.setBackgroundColor(Color.WHITE);p.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
 private void savePlan(){prefs.edit().putInt("standard",standard.getSelectedItemPosition()).putString("organisation",organisation.getText().toString()).putString("responsable",responsable.getText().toString()).putString("sources",sources.getText().toString()).putString("quality",quality.getText().toString()).putString("sharing",sharing.getText().toString()).putString("retention",retention.getText().toString()).putString("target",target.getText().toString()).putString("schedule",schedule.getText().toString()).apply();Toast.makeText(this,"Plan enregistré localement",Toast.LENGTH_SHORT).show();}
 private void shareSummary(){savePlan();String x="Culture du Québec — Projet de standardisation\nNorme : "+standard.getSelectedItem()+"\nOrganisation : "+organisation.getText()+"\nResponsable : "+responsable.getText()+"\nSources : "+sources.getText()+"\nQualité : "+quality.getText()+"\nPartage : "+sharing.getText()+"\nConservation : "+retention.getText()+"\nCible : "+target.getText()+"\nÉchéancier : "+schedule.getText()+"\n\nDocument de travail — aucune certification officielle.";Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,x);startActivity(Intent.createChooser(i,"Partager"));}
 private void applyInsets(View v){v.setOnApplyWindowInsetsListener((q,in)->{android.graphics.Insets b=in.getInsets(WindowInsets.Type.systemBars());q.setPadding(dp(18),dp(18)+b.top,dp(18),dp(30)+b.bottom);return in;});v.requestApplyInsets();}private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackgroundResource(R.drawable.panel);return p;}private TextView text(String s,int z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(b)t.setTypeface(android.graphics.Typeface.DEFAULT,1);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundResource(R.drawable.button_primary);return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,59,113));b.setBackgroundResource(R.drawable.button_secondary);return b;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}