package quebec.culture.donnees;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.Bundle;import android.view.*;import android.widget.*;

public class TeamCapacityActivity extends Activity{
 private SharedPreferences prefs;private LinearLayout root;private EditText lead,leadExp,dataLead,dataExp,techLead,techExp,partners,external,governance,continuity,training;
 @Override protected void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("team_capacity",MODE_PRIVATE);getWindow().setStatusBarColor(Color.rgb(0,40,77));getWindow().setNavigationBarColor(Color.rgb(0,40,77));setContentView(build());}
 private View build(){ScrollView s=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(30));root.setBackgroundColor(Color.rgb(245,247,250));s.addView(root);applyInsets(root);root.addView(text("Équipe et capacité de réalisation",28,Color.rgb(0,59,113),true));root.addView(text("Documentez ici les personnes, compétences, responsabilités et capacités internes/externes qui soutiennent la faisabilité du projet.",14,Color.DKGRAY,false),mb());
  LinearLayout p=panel();lead=field(p,"Responsable du projet","lead");leadExp=field(p,"Expérience et rôle du responsable","leadExp");dataLead=field(p,"Responsable des données / métadonnées","dataLead");dataExp=field(p,"Compétences en gestion de données et normalisation","dataExp");techLead=field(p,"Responsable technique","techLead");techExp=field(p,"Compétences techniques, formats, bases de données, Android/API","techExp");partners=field(p,"Partenaires et collaborateurs","partners");external=field(p,"Sous-traitants / consultants prévus et mandat","external");governance=field(p,"Gouvernance : qui valide quoi et à quel moment","governance");continuity=field(p,"Continuité après la subvention : maintien, mises à jour, sauvegardes","continuity");training=field(p,"Besoins de formation et transfert de connaissances","training");Button save=primary("Enregistrer l’équipe et les capacités");save.setOnClickListener(v->save());p.addView(save);Button share=secondary("Partager la fiche équipe/capacité");share.setOnClickListener(v->share());p.addView(share);root.addView(p);return s;}
 private EditText field(LinearLayout p,String l,String k){p.addView(text(l,13,Color.rgb(21,37,54),true));EditText e=new EditText(this);e.setText(prefs.getString(k,""));e.setHint(l);e.setMinLines(2);e.setGravity(Gravity.TOP|Gravity.START);e.setBackgroundColor(Color.WHITE);e.setPadding(dp(10),dp(8),dp(10),dp(8));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(10);p.addView(e,lp);return e;}
 private void save(){prefs.edit().putString("lead",lead.getText().toString()).putString("leadExp",leadExp.getText().toString()).putString("dataLead",dataLead.getText().toString()).putString("dataExp",dataExp.getText().toString()).putString("techLead",techLead.getText().toString()).putString("techExp",techExp.getText().toString()).putString("partners",partners.getText().toString()).putString("external",external.getText().toString()).putString("governance",governance.getText().toString()).putString("continuity",continuity.getText().toString()).putString("training",training.getText().toString()).apply();Toast.makeText(this,"Équipe et capacités enregistrées",Toast.LENGTH_SHORT).show();}
 private void share(){save();String x="Culture du Québec — Équipe et capacité de réalisation\n\nResponsable : "+lead.getText()+"\nExpérience/rôle : "+leadExp.getText()+"\n\nResponsable données : "+dataLead.getText()+"\nCompétences données : "+dataExp.getText()+"\n\nResponsable technique : "+techLead.getText()+"\nCompétences techniques : "+techExp.getText()+"\n\nPartenaires : "+partners.getText()+"\nSous-traitants : "+external.getText()+"\nGouvernance : "+governance.getText()+"\nContinuité : "+continuity.getText()+"\nFormation : "+training.getText()+"\n\nDocument de travail — à adapter au dossier officiel.";Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,x);startActivity(Intent.createChooser(i,"Partager"));}
 private void applyInsets(View v){v.setOnApplyWindowInsetsListener((q,in)->{android.graphics.Insets b=in.getInsets(WindowInsets.Type.systemBars());q.setPadding(dp(18),dp(18)+b.top,dp(18),dp(30)+b.bottom);return in;});v.requestApplyInsets();}private LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(16),dp(16),dp(16),dp(16));p.setBackgroundResource(R.drawable.panel);return p;}private TextView text(String s,int z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(b)t.setTypeface(android.graphics.Typeface.DEFAULT,1);return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundResource(R.drawable.button_primary);return b;}private Button secondary(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.rgb(0,59,113));b.setBackgroundResource(R.drawable.button_secondary);return b;}private LinearLayout.LayoutParams mb(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(14);return p;}private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}