plugins { id 'com.android.application' }

android {
    namespace 'quebec.lanaudiere.essence'
    compileSdk 35

    defaultConfig {
        applicationId 'quebec.lanaudiere.essence'
        minSdk 26
        targetSdk 35
        versionCode 28
        versionName '1.7.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
