plugins { id 'com.android.application' }

android {
    namespace 'quebec.detecteur360'
    compileSdk 35

    defaultConfig {
        applicationId 'quebec.detecteur360.qc'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '3.0.0'
    }

    buildTypes {
        debug { }
        release { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
