plugins { id 'com.android.application' }

android {
    namespace 'quebec.detecteur360'
    compileSdk 35

    defaultConfig {
        applicationId 'quebec.detecteur360.qc'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '3.0.0'
    }

    signingConfigs {
        stable {
            storeFile rootProject.file('d360-release.jks')
            storePassword 'D360Quebec2026!'
            keyAlias 'd360'
            keyPassword 'D360Quebec2026!'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.stable
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.stable
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
