package ca.quebec.oui;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.WindowInsets;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.TextView;
import java.text.DecimalFormat;
import java.util.Locale;

public class MainActivity extends Activity {
    private static final int BLUE=Color.rgb(0,61,165), DARK=Color.rgb(0,31,91), NAVY=Color.rgb(8,22,55), INK=Color.rgb(20,33,61), MUTED=Color.rgb(92,108,135), SOFT=Color.rgb(244,247,252), BORDER=Color.rgb(220,228,241), OFFICIAL=Color.rgb(18,126,72), CALC=Color.rgb(41,96,190), ESTIMATE=Color.rgb(194,104,16), PURPLE=Color.rgb(111,70,160), WHITE=Color.WHITE;
    private LinearLayout content;
    private final DecimalFormat one=new DecimalFormat("0.0");

    private static final String[] CHAPTER_TITLES = {
        "1. Une question de liberté et d’identité","2. Le Québec freiné dans son élan","3. Le Canada a eu ses chances","4. La consultation","5. La transition vers la fin d’un gouvernement de trop","6. Les institutions d’un Québec indépendant","7. L’architecture financière d’un Québec indépendant","8. Une économie nationale plus agile avec l’indépendance","9. Des finances publiques libres et simplifiées","10. Les relations internationales du Québec indépendant","11. Les relations du Québec indépendant avec le Canada et les provinces","12. La citoyenneté québécoise","13. Frontières, défense et sécurité nationale","14. Une langue française vivante et une culture rayonnante","15. Communications et indépendance numérique","16. L’environnement et les transports","17. Agriculture et pêcheries","18. Ressources naturelles et énergie","19. Prendre soin de son monde sans conditions","20. Justice","21. Les droits des minorités","22. Les relations avec les Premières Nations et les Inuit"
    };
    private static final String[] CHAPTER_PAGES = {"3","43","65","95","119","153","181","205","227","243","273","291","303","327","341","361","383","395","403","423","447","457"};
    private static final String[] CHAPTER_SUMMARIES = {
        "Langue, identité, multiculturalisme, fait religieux, Constitution de 1982 et avenir de la nation québécoise dans la fédération. Le Livre bleu soutient que la pérennité du français et l’autonomie politique exigent l’indépendance.",
        "Analyse du régime monarchique, de la Constitution de 1867 et de la Charte canadienne. Le chapitre présente le fédéralisme comme un cadre qui limite les choix économiques, culturels et linguistiques du Québec.",
        "Parcours historique de la Conquête à l’après-2003 : Patriotes, Confédération, guerres mondiales, Révolution tranquille et tentatives d’autonomie. La thèse du chapitre est que les réformes constitutionnelles ont échoué à répondre aux demandes du Québec.",
        "Référendum, formulation de la question, majorité requise, Renvoi relatif à la sécession, Loi sur la clarté, reconnaissance d’un résultat et mesures proposées pour protéger l’intégrité démocratique du processus.",
        "Transition après une victoire du Oui : territoire, continuité juridique, constitution provisoire, capitale, continuité des paiements, négociation des actifs et passifs, réorganisation administrative, intégration de fonctionnaires fédéraux, Outaouais et personnalité internationale.",
        "Constitution d’un Québec indépendant, assemblée constituante, république, séparation et organisation des pouvoirs, rôle du chef de l’État et contre-pouvoirs. Le Livre bleu ne prétend pas fixer définitivement la future constitution.",
        "Options monétaires, banque centrale, continuité de la réglementation financière, systèmes internationaux, accords de Bâle et possibilité d’une monnaie québécoise. Le document présente plusieurs trajectoires plutôt qu’un seul mécanisme instantané.",
        "Portrait des forces économiques du Québec et arguments selon lesquels le contrôle complet des politiques économiques, commerciales et réglementaires rendrait l’économie plus agile.",
        "Budgets d’un Québec indépendant, fiscalité, déséquilibre fiscal, cote de crédit et simplification institutionnelle. Les projections financières du Livre bleu sont des scénarios politiques et non des comptes publics officiels.",
        "Personnalité internationale, réseau diplomatique, relations avec les États-Unis, Saint-Laurent, commerce, organisations multilatérales et Francophonie. Le Livre bleu prévoit une diplomatie québécoise complète mais plus légère que celle du Canada.",
        "Institutions Québec-Canada, libre-échange, libre circulation des personnes et des capitaux, coopération économique, union douanière, travail, infrastructures communes, Gatineau-Ottawa et lieux de mémoire conjoints.",
        "Création d’une citoyenneté québécoise, naturalisation, place des francophones du Canada, double citoyenneté et maintien éventuel de la citoyenneté canadienne selon le droit canadien et les négociations.",
        "Gestion des frontières avec le Canada et les États-Unis, actifs frontaliers, politique migratoire, passeport, sécurité nationale, forces armées, OTAN, NORAD et coopération de défense. Aucun service militaire obligatoire n’est proposé.",
        "Promotion du français, politique culturelle, symboles nationaux, accès à la culture, institutions culturelles nationales, radiodiffusion, partenariats avec les Nations autochtones et rayonnement de la création québécoise.",
        "Télécommunications, radiodiffusion, souveraineté numérique, rôle de Radio-Canada, réglementation et marché mobile. Le chapitre propose de rapatrier les leviers de communications et de créer des institutions québécoises.",
        "Partage actuel des responsabilités environnementales et de transport, réglementation, infrastructures et simplification de la prise de décision dans un Québec indépendant.",
        "Chevauchements administratifs en agriculture et en pêcheries, financement agricole, propriété et gestion des ressources halieutiques. Le Livre bleu propose de regrouper ces fonctions au Québec.",
        "Ressources naturelles, énergie, compétences fédérales résiduelles et exemples de chevauchements. Le chapitre présente l’indépendance comme un moyen de réunir les leviers liés au territoire, aux ressources et à l’énergie.",
        "Assurance-emploi, prestations fédérales, pouvoir fédéral de dépenser, santé, protection du consommateur et marché du travail. Le document propose la continuité des prestations existantes au moment de l’indépendance, prises en charge par Québec.",
        "Organisation des tribunaux, nomination des juges, Cour du Québec et Cour supérieure, droit civil, droit criminel, délais judiciaires et prisons. Le Livre bleu propose une architecture judiciaire entièrement québécoise.",
        "Continuité des protections existantes : Charte québécoise, Commission et Tribunal des droits, égalité en emploi, personnes handicapées et équité salariale. Le document prévoit de constitutionnaliser une partie importante des droits.",
        "Relations de nation à nation, continuité des droits, traités et ententes, langues et cultures autochtones. Le chapitre traite séparément les Premières Nations et les Inuit dans la construction d’un Québec indépendant."
    };
    private static final String[] SUBSECTIONS = {
        "Ch.1 : langue • avenir du français • Charte de la langue française • multiculturalisme • fait religieux • affaire Amselem • Constitution de 1982",
        "Ch.2 : monarque • 1867 • impasse constitutionnelle • Charte canadienne • nationalisme constitutionnel • carcan économique et fiscal • frein culturel et linguistique",
        "Ch.3 : Conquête • Patriotes • 1867 • deux nations fondatrices • guerres mondiales • Duplessis • Johnson • Lesage • Révolution tranquille • après 2003",
        "Ch.4 : standards démocratiques • référendum • question • Renvoi sur la sécession • Loi sur la clarté • majorité • reconnaissance • garde-fous • ingérence extérieure",
        "Ch.5 : transition • marchés • territoire • partition • continuité juridique • constitution provisoire • capitale • paiements fédéraux • actifs/passifs • bureaucratie • fonctionnaires fédéraux • Outaouais",
        "Ch.6 : constitution • constituante • république • gauche/droite • trois pouvoirs • exécutif/législatif • contre-pouvoirs",
        "Ch.7 : monnaie • banque centrale • politique monétaire • continuité financière • FMI • Banque mondiale • OMC • BRI • accords de Bâle",
        "Ch.8 : forces de l’économie • avantages de l’indépendance • agilité économique",
        "Ch.9 : budgets • fiscalité • déséquilibre fiscal • cote de crédit • simplification démocratique",
        "Ch.10 : relations internationales • États-Unis • Saint-Laurent • commerce • personnalité internationale • multilatéralisme • OIF • diplomatie",
        "Ch.11 : institutions Québec-Canada • libre-échange • libre circulation • capitaux • union douanière • travail • infrastructures • Gatineau-Ottawa",
        "Ch.12 : citoyenneté • clause Canada • francophones du Canada • double citoyenneté • citoyenneté multiple",
        "Ch.13 : frontières • actifs frontaliers • États-Unis • immigration • passeport • défense • forces armées • OTAN • NORAD",
        "Ch.14 : langue nationale • culture • symboles • accès • institutions culturelles • Nations autochtones • diversité • créativité",
        "Ch.15 : communications • Radio-Canada • téléphonie mobile • réglementation • indépendance numérique",
        "Ch.16 : environnement • transports • infrastructures • simplification décisionnelle",
        "Ch.17 : agriculture • financement • Financière agricole • pêcheries • permis",
        "Ch.18 : ressources naturelles • énergie • partage des compétences",
        "Ch.19 : prestations • assurance-emploi • pouvoir de dépenser • santé • protection du consommateur • travail",
        "Ch.20 : tribunaux • juges • Cour supérieure • droit civil • droit criminel • arrêt Jordan • prisons",
        "Ch.21 : Charte québécoise • minorité anglophone • minorités visibles et culturelles • diversité sexuelle et de genre",
        "Ch.22 : Premières Nations • Inuit • relations de nation à nation • droits • langues • culture",
        "Annexe I : Le régime de 1867 dénudé","Annexe II : Projet de constitution provisoire","Annexe III : Ministères et organismes fédéraux du Canada et leur place dans un Québec indépendant"
    };

    @Override public void onCreate(Bundle b){super.onCreate(b);Locale.setDefault(Locale.CANADA_FRENCH);shell();home();}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    private GradientDrawable bordered(int color,int stroke){GradientDrawable g=bg(color,16);g.setStroke(dp(1),stroke);return g;}
    private TextView tx(String s,int sp,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(c);t.setLineSpacing(0,1.08f);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private Button nav(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextColor(WHITE);b.setTextSize(13);b.setAllCaps(false);b.setBackground(bg(BLUE,14));b.setPadding(dp(14),0,dp(14),0);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,dp(44));lp.setMargins(dp(4),0,dp(4),0);b.setLayoutParams(lp);b.setOnClickListener(l);return b;}

    private void applySafeInsets(LinearLayout root){
        if(Build.VERSION.SDK_INT>=30){
            getWindow().setDecorFitsSystemWindows(false);
            root.setOnApplyWindowInsetsListener((v,insets)->{
                android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars() | WindowInsets.Type.displayCutout());
                v.setPadding(bars.left,bars.top,bars.right,bars.bottom);
                return insets;
            });
        }
    }

    private void shell(){
        getWindow().setStatusBarColor(DARK);getWindow().setNavigationBarColor(DARK);
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(WHITE);applySafeInsets(root);
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.VERTICAL);head.setPadding(dp(18),dp(18),dp(18),dp(15));head.setBackgroundColor(DARK);
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(tx("⚜",30,WHITE,true));TextView title=tx("  OUI QUÉBEC",26,WHITE,true);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView ver=tx("V4.1",12,Color.rgb(204,220,255),true);ver.setPadding(dp(9),dp(5),dp(9),dp(5));ver.setBackground(bg(Color.rgb(17,56,125),12));top.addView(ver);head.addView(top);
        TextView sub=tx("Données publiques, scénarios, Livre bleu et ressources citoyennes",13,Color.rgb(212,225,250),false);sub.setPadding(0,dp(5),0,0);head.addView(sub);root.addView(head);
        HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);hs.setBackgroundColor(Color.rgb(237,243,253));LinearLayout n=new LinearLayout(this);n.setPadding(dp(8),dp(8),dp(8),dp(8));
        n.addView(nav("Accueil",v->home()));n.addView(nav("Livre bleu",v->book()));n.addView(nav("OUI Québec",v->ouiQuebec()));n.addView(nav("Données",v->bookData()));n.addView(nav("Québec–Canada",v->comparisons()));n.addView(nav("Simulation",v->simulation()));n.addView(nav("Sources",v->sources()));hs.addView(n);root.addView(hs);
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setClipToPadding(false);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(15),dp(16),dp(15),dp(34));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
    }

    private void reset(String h,String s){content.removeAllViews();content.addView(tx(h,25,NAVY,true));TextView sub=tx(s,14,MUTED,false);sub.setPadding(0,dp(4),0,dp(14));content.addView(sub);}
    private void section(String title,String sub){TextView h=tx(title,19,NAVY,true);h.setPadding(0,dp(10),0,dp(2));content.addView(h);TextView s=tx(sub,13,MUTED,false);s.setPadding(0,0,0,dp(9));content.addView(s);}
    private TextView badge(String s,int color){TextView t=tx(s,10,color,true);t.setPadding(dp(8),dp(4),dp(8),dp(4));t.setBackground(bordered(WHITE,BORDER));return t;}
    private void card(String title,String big,String detail,int color,String label){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(15),dp(13),dp(15),dp(13));b.setBackground(bordered(SOFT,BORDER));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(10));b.setLayoutParams(lp);b.addView(tx(title,13,MUTED,true));TextView v=tx(big,25,NAVY,true);v.setPadding(0,dp(2),0,dp(3));b.addView(v);b.addView(tx(detail,13,INK,false));TextView tag=badge(label,color);LinearLayout.LayoutParams tlp=new LinearLayout.LayoutParams(-2,-2);tlp.setMargins(0,dp(8),0,0);tag.setLayoutParams(tlp);b.addView(tag);content.addView(b);}
    private void infoBox(String s,int color){TextView t=tx(s,12,color,true);t.setPadding(dp(12),dp(10),dp(12),dp(10));t.setBackground(bordered(WHITE,BORDER));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(10));t.setLayoutParams(lp);content.addView(t);}

    private void home(){reset("Tableau de bord","OUI Québec V4.1 distingue les données gouvernementales, les calculs de l’application, le Livre bleu du Parti Québécois et les ressources d’organisations citoyennes.");card("Livre bleu intégré","22 chapitres + 3 annexes","Navigation thématique, index des sous-sections, portrait statistique et synthèse des orientations du document de 550 pages.",PURPLE,"● SOURCE PARTISANE — LIVRE BLEU");card("Section OUI Québec","Nouvelle","Mission, organisation, initiatives et accès direct au Plan d’action 2025-2026 des Organisations unies pour l’indépendance.",PURPLE,"● SOURCE — OUI QUÉBEC");card("Revenus du Québec 2026-2027","166,492 G$","134,361 G$ de revenus autonomes + 32,131 G$ de transferts fédéraux.",OFFICIAL,"● DONNÉE OFFICIELLE");card("Dépenses du Québec 2026-2027","170,757 G$","160,489 G$ de dépenses de portefeuilles + 10,268 G$ de service de la dette.",OFFICIAL,"● DONNÉE OFFICIELLE");card("Principaux transferts fédéraux","30,256 G$","Santé 12,457 G$ • social 3,892 G$ • péréquation 13,907 G$.",OFFICIAL,"● DONNÉE OFFICIELLE");infoBox("Affichage sécurisé : l’interface tient maintenant compte des barres système Android et des découpes d’écran pour éviter que le contenu passe sous la barre d’état ou la navigation.",CALC);}

    private void book(){reset("Livre bleu — 550 pages","Index complet par chapitre. Utilise la recherche pour retrouver rapidement un thème.");EditText search=new EditText(this);search.setHint("Rechercher : monnaie, OTAN, citoyenneté, langue, dette...");search.setSingleLine(true);search.setTextColor(INK);search.setHintTextColor(MUTED);search.setBackground(bordered(WHITE,BORDER));search.setPadding(dp(12),0,dp(12),0);content.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams rlp=new LinearLayout.LayoutParams(-1,-2);rlp.setMargins(0,dp(12),0,0);content.addView(results,rlp);Runnable render=()->renderBookResults(results,search.getText().toString());render.run();search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){render.run();}public void afterTextChanged(Editable e){}});}
    private void renderBookResults(LinearLayout holder,String q){holder.removeAllViews();String needle=q.trim().toLowerCase(Locale.CANADA_FRENCH);int shown=0;for(int i=0;i<CHAPTER_TITLES.length;i++){String hay=(CHAPTER_TITLES[i]+" "+CHAPTER_SUMMARIES[i]+" "+SUBSECTIONS[i]).toLowerCase(Locale.CANADA_FRENCH);if(needle.length()==0||hay.contains(needle)){bookCard(holder,CHAPTER_TITLES[i],"Page imprimée "+CHAPTER_PAGES[i],CHAPTER_SUMMARIES[i],SUBSECTIONS[i]);shown++;}}for(int i=22;i<SUBSECTIONS.length;i++){if(needle.length()==0||SUBSECTIONS[i].toLowerCase(Locale.CANADA_FRENCH).contains(needle)){bookCard(holder,SUBSECTIONS[i],"Annexe","Annexe intégrée à l’index du Livre bleu.","");shown++;}}if(shown==0){TextView none=tx("Aucun thème trouvé. Essaie un mot plus général.",14,MUTED,true);none.setPadding(0,dp(14),0,0);holder.addView(none);}}
    private void bookCard(LinearLayout holder,String title,String page,String summary,String topics){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(14),dp(13),dp(14),dp(13));b.setBackground(bordered(SOFT,BORDER));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(10));b.setLayoutParams(lp);b.addView(tx(title,17,NAVY,true));TextView p=tx(page,11,PURPLE,true);p.setPadding(0,dp(3),0,dp(6));b.addView(p);b.addView(tx(summary,13,INK,false));if(topics.length()>0){TextView t=tx(topics,11,MUTED,false);t.setPadding(0,dp(7),0,0);b.addView(t);}TextView tag=tx("● POSITION / PROJECTION DU LIVRE BLEU",10,PURPLE,true);tag.setPadding(0,dp(8),0,0);b.addView(tag);holder.addView(b);}

    private void ouiQuebec(){reset("OUI Québec","Organisations unies pour l’indépendance — section documentaire distincte du Parti Québécois et des données gouvernementales.");card("Mission","Mobiliser la société civile","OUI Québec se présente comme une organisation citoyenne non partisane qui cherche à engager la société civile autour du projet d’indépendance du Québec.",PURPLE,"● INFORMATION DE L’ORGANISATION");card("Structure","13 tables régionales","Le site de l’organisation indique aussi cinq comités thématiques et une représentation provenant de mouvements sociaux, d’organisations indépendantistes et de citoyens.",PURPLE,"● INFORMATION DE L’ORGANISATION");card("Financement","100 % société civile","OUI Québec affirme que ses activités sont financées entièrement par la société civile et les contributions citoyennes.",PURPLE,"● DÉCLARATION DE L’ORGANISATION");section("Plan d’action 2025-2026","Accès au document transmis. Le contenu est présenté comme celui d’une organisation militante et non comme une source gouvernementale.");source("Plan d’action 2025-2026","Document PDF publié par OUI Québec.","https://static1.squarespace.com/static/63fad0fd466db43e7889817c/t/689b56e7cabff9423eadaa9f/1755010791584/Plan+d%27action+2025.pdf");section("Initiatives publiques","Éléments présentés sur le site de l’organisation.");card("Consultation de la société civile","2026","OUI Québec indique avoir analysé des mémoires publics et rencontré plus de 50 représentants d’organisations dans un projet de consultation multisectorielle.",PURPLE,"● INFORMATION DE L’ORGANISATION");card("Tournée citoyenne","23+ dates annoncées","Le site annonce une tournée de la nouvelle édition du « Livre qui fait dire OUI », incluant plusieurs cégeps et universités, avec 10 000 exemplaires à distribuer gratuitement.",PURPLE,"● INFORMATION DE L’ORGANISATION");card("Mobilisation jeunesse","10 000+ jeunes revendiqués","L’organisation affirme avoir interpellé ou mobilisé plus de 10 000 jeunes à travers des événements politico-culturels sur quatre ans.",PURPLE,"● DÉCLARATION DE L’ORGANISATION");source("Site officiel OUI Québec","Mission, équipe, comités, tables régionales, documents et activités.","https://www.ouiquebec.org/");source("Documents et bilans","Plans d’action, bilans et statuts publiés par l’organisation.","https://www.ouiquebec.org/documents-et-bilans");infoBox("Cette section ne transforme pas les objectifs ou chiffres revendiqués par OUI Québec en données officielles. Les libellés indiquent clairement leur provenance.",PURPLE);}

    private void bookData(){reset("Livre bleu — Québec en un coup d’œil","Données synthétisées à partir des tableaux du Livre bleu; les années de référence sont conservées.");section("Territoire et démographie","Portrait des pages xxi à xxv.");card("Superficie","1,67 M km²","17e rang mondial indiqué; environ 10 % du territoire en eau douce; frontières : 12 000 km.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");card("Population — janvier 2025","9,1 M","21,9 % du Canada; densité 2024 : 7 hab./km²; âge moyen : 42,8 ans.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");card("Espérance de vie — 2024","82,7 ans","Le document indique le 1er rang au Canada.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");section("Langues","Recensement 2021 et étude 2024 cités.");card("Français — langue maternelle","76,3 %","Tout le Québec en 2021; langue parlée le plus souvent à la maison : 79,1 %.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");card("Montréal — langue maternelle française","46,5 %","Région administrative de Montréal en 2021; français à la maison : 51,5 %.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");section("Premières Nations et Inuit","Tableau 2023.");card("Communautés et population","59 • 125 163 personnes","Ventilation de 11 nations/groupes et des Inuit dans le document.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");section("Éducation et développement","Indicateurs du portrait statistique.");card("25-34 ans avec diplôme postsecondaire — 2024","79,5 %","Comparatif du reste du Canada : 76,5 %.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");card("Revenu moyen total — 2022","55 200 $","Revenu d’emploi moyen : 52 545 $; revenu moyen après impôt des ménages : 83 949 $.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");card("Taux de pauvreté — 2022","6,6 %","Le document indique le 1er rang au Canada; Gini après impôt : 0,27.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");section("Économie et commerce — 2024","Valeurs du portrait statistique.");card("Exportations","124,141 G$","Aéronefs, aluminium, minerai de fer, moteurs d’aéronefs et métaux précieux figurent parmi les principaux produits.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");card("Importations","127,455 G$","Principales provenances citées : États-Unis, Chine, Mexique, Allemagne et France.",PURPLE,"● DONNÉE CITÉE PAR LE LIVRE BLEU");}

    private void comparisons(){reset("Québec–Canada","Une compétence transférée n’est pas automatiquement une économie : les services nationaux nécessaires doivent continuer d’exister.");card("Fiscalité","Deux administrations","Revenu Québec et l’ARC exercent des fonctions parallèles; un guichet unique peut réduire certains frais.",CALC,"● ANALYSE / CALCUL");card("Immigration","Compétences partagées","Le Livre bleu prévoit que Québec reprenne citoyenneté, visas et admission finale.",PURPLE,"● POSITION DU LIVRE BLEU");card("Actifs et dette fédérale","Négociation","Le Livre bleu propose de négocier ensemble le partage des actifs et une part de la dette fédérale; la dette fédérale n’est pas présentée comme une obligation automatique du Québec.",PURPLE,"● POSITION DU LIVRE BLEU");card("Fonctionnaires fédéraux","Intégration ciblée","Le document prévoit intégrer les employés dont les fonctions sont nécessaires au nouvel État.",PURPLE,"● POSITION DU LIVRE BLEU");card("Prestations fédérales","Continuité proposée","Le document propose de reconduire les paiements de transfert existants et de les prendre en charge par Québec après la transition.",PURPLE,"● PROPOSITION DU LIVRE BLEU");}

    private void simulation(){reset("Simulateur Québec pays","Outil exploratoire; aucun résultat n’est une prévision officielle.");final double baseRevenue=134.361,baseExpense=170.757;final TextView result=tx("",25,NAVY,true);final int[] vals={90,65,4,3};String[] names={"Revenus fédéraux attribuables au Québec","Nouvelles fonctions d’un État","Économies de regroupement","Coûts de transition"};int[] max={140,100,20,20};for(int i=0;i<4;i++){final int k=i;TextView lab=tx("",14,INK,true);content.addView(lab);SeekBar s=new SeekBar(this);s.setMax(max[i]);s.setProgress(vals[i]);content.addView(s);Runnable up=()->{lab.setText(names[k]+" : "+vals[k]+" G$");double r=baseRevenue+vals[0]-baseExpense-vals[1]+vals[2]-vals[3];result.setText("Solde simulé : "+(r>=0?"+":"")+one.format(r)+" G$");};up.run();s.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean u){vals[k]=p;up.run();}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});}result.setPadding(dp(14),dp(14),dp(14),dp(14));result.setBackground(bordered(SOFT,BORDER));content.addView(result);infoBox("Les curseurs sont des hypothèses. Les chapitres 5, 7 et 9 du Livre bleu servent de référence politique seulement.",ESTIMATE);}

    private void source(String title,String desc,String url){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(14),dp(12),dp(14),dp(12));b.setBackground(bordered(SOFT,BORDER));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(9));b.setLayoutParams(lp);b.addView(tx(title,16,NAVY,true));TextView d=tx(desc,12,MUTED,false);d.setPadding(0,dp(3),0,dp(7));b.addView(d);if(url!=null&&url.length()>0){Button o=new Button(this);o.setText("Ouvrir la source");o.setTextColor(WHITE);o.setAllCaps(false);o.setBackground(bg(BLUE,12));o.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url))));b.addView(o);}content.addView(b);}
    private void sources(){reset("Sources","Les sources partisanes, citoyennes, gouvernementales et les hypothèses de calcul sont distinguées.");source("Livre bleu sur l’indépendance du Québec","Document du Parti Québécois, édition 2026, 550 pages. Intégré sous forme d’index, de synthèses thématiques et de données citées.","");source("OUI Québec — Plan d’action 2025-2026","Document de l’organisation citoyenne OUI Québec.","https://static1.squarespace.com/static/63fad0fd466db43e7889817c/t/689b56e7cabff9423eadaa9f/1755010791584/Plan+d%27action+2025.pdf");source("OUI Québec — documents et bilans","Page officielle regroupant plans d’action, bilans et statuts.","https://www.ouiquebec.org/documents-et-bilans");source("Budget du Québec 2026-2027","Cadre financier, revenus et dépenses.","https://www.finances.gouv.qc.ca/Budget_et_mise_a_jour/budget/");source("Principaux transferts fédéraux","Finances Canada — transferts vers le Québec.","https://www.canada.ca/fr/ministere-finances/programmes/transferts-federaux/principaux-transferts-federaux.html");source("Comptes publics du Canada 2025","États financiers consolidés du gouvernement fédéral.","https://www.canada.ca/fr/services-publics-approvisionnement/services/paiements-comptabilite/comptes-publics/2025.html");TextView foot=tx("OUI Québec 4.1 • Mise à jour : 9 septembre 2026",12,MUTED,true);foot.setGravity(Gravity.CENTER);foot.setPadding(0,dp(14),0,0);content.addView(foot);}
}
