package com.nexusduo.app;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.*;import android.view.*;import android.webkit.*;import android.widget.*;
public class BrowserActivity extends Activity{
 WebView w; int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} TextView b(String s){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(20);t.setGravity(Gravity.CENTER);t.setPadding(dp(10),0,dp(10),0);return t;}
 @Override public void onCreate(Bundle x){super.onCreate(x);String name=getIntent().getStringExtra("name"),url=getIntent().getStringExtra("url");LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(8,10,15));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(4),0,dp(4),0);TextView back=b("‹");TextView title=b(name);title.setTextSize(16);title.setTypeface(null,1);TextView refresh=b("↻");TextView ext=b("↗");bar.addView(back,new LinearLayout.LayoutParams(dp(52),dp(54)));bar.addView(title,new LinearLayout.LayoutParams(0,dp(54),1));bar.addView(refresh,new LinearLayout.LayoutParams(dp(52),dp(54)));bar.addView(ext,new LinearLayout.LayoutParams(dp(52),dp(54)));root.addView(bar);
 w=new WebView(this);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setUserAgentString(s.getUserAgentString().replace("; wv", ""));CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(w,true);w.setWebChromeClient(new WebChromeClient());w.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();String sch=u.getScheme();if("http".equals(sch)||"https".equals(sch))return false;try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){}return true;}});root.addView(w,new LinearLayout.LayoutParams(-1,0,1));back.setOnClickListener(v->{if(w.canGoBack())w.goBack();else finish();});refresh.setOnClickListener(v->w.reload());ext.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(w.getUrl())));}catch(Exception e){}});w.loadUrl(url);setContentView(root); }
 @Override public void onBackPressed(){if(w!=null&&w.canGoBack())w.goBack();else super.onBackPressed();}
 @Override protected void onDestroy(){if(w!=null){w.stopLoading();w.destroy();}super.onDestroy();}
}
