package com.nexusduo.app;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;
public class DashboardActivity extends Activity{
 int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} TextView tv(String s,int z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}
 String[][] apps={{"TikTok","♪","https://www.tiktok.com/"},{"Instagram","◎","https://www.instagram.com/"},{"Facebook","f","https://www.facebook.com/"},{"X","𝕏","https://x.com/"},{"Twitch","▣","https://www.twitch.tv/"},{"YouTube","▶","https://m.youtube.com/"},{"Snapchat","◉","https://www.snapchat.com/"},{"Pinterest","P","https://www.pinterest.com/"},{"Reddit","●","https://www.reddit.com/"},{"Threads","@","https://www.threads.net/"},{"LinkedIn","in","https://www.linkedin.com/"},{"Discord","◈","https://discord.com/app"}};
 @Override public void onCreate(Bundle b){super.onCreate(b);int p=getSharedPreferences("nexus",0).getInt("profile",0);ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(34),dp(18),dp(30));root.setBackgroundColor(Color.rgb(8,10,15));
 LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=tv("NEXUS DUO",24,Color.WHITE);title.setTypeface(null,1);top.addView(title,new LinearLayout.LayoutParams(0,dp(52),1));TextView who=tv(p==0?"MON ESPACE":"SON ESPACE",12,p==0?Color.rgb(124,92,252):Color.rgb(236,72,153));who.setGravity(Gravity.CENTER);top.addView(who,new LinearLayout.LayoutParams(dp(100),dp(52)));root.addView(top);
 TextView h=tv("Tous vos réseaux",28,Color.WHITE);h.setTypeface(null,1);h.setPadding(0,dp(14),0,0);root.addView(h,new LinearLayout.LayoutParams(-1,dp(62)));TextView sub=tv("Touchez un service : sa fiche vous montre comment l’ouvrir ou l’intégrer dans Nexus Duo.",14,Color.rgb(156,163,175));root.addView(sub,new LinearLayout.LayoutParams(-1,dp(64)));
 GridLayout grid=new GridLayout(this);grid.setColumnCount(3);for(String[] a:apps){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER);card.setPadding(dp(4),dp(8),dp(4),dp(6));card.setBackground(bg(Color.rgb(21,25,37),18));TextView ic=tv(a[1],28,Color.WHITE);ic.setGravity(Gravity.CENTER);ic.setTypeface(null,1);TextView nm=tv(a[0],12,Color.rgb(230,232,238));nm.setGravity(Gravity.CENTER);card.addView(ic,new LinearLayout.LayoutParams(-1,dp(48)));card.addView(nm,new LinearLayout.LayoutParams(-1,dp(28)));card.setOnClickListener(v->{Intent i=new Intent(this,NetworkActivity.class);i.putExtra("name",a[0]);i.putExtra("url",a[2]);startActivity(i);});GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=dp(94);gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);gp.setMargins(dp(5),dp(5),dp(5),dp(5));grid.addView(card,gp);}root.addView(grid,new LinearLayout.LayoutParams(-1,-2));
 TextView privacy=tv("🔒  Mode privé local\nAucun compte Nexus, aucune télémétrie ajoutée par l’app.",13,Color.rgb(180,185,197));privacy.setPadding(dp(16),dp(16),dp(16),dp(16));privacy.setBackground(bg(Color.rgb(21,25,37),18));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(88));pp.setMargins(0,dp(22),0,0);root.addView(privacy,pp);sv.addView(root);setContentView(sv); }
}
