package com.nexusduo.app;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.view.animation.*;import android.widget.*;
public class MainActivity extends Activity{
 int BLUE=Color.rgb(0,61,165),CYAN=Color.rgb(0,184,255),INK=Color.rgb(18,38,72),MUTED=Color.rgb(92,112,145);int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER);return t;} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));g.setStroke(dp(1),Color.rgb(214,228,250));return g;} void pop(View v,long d){v.setAlpha(0);v.setTranslationY(dp(18));v.animate().alpha(1).translationY(0).setStartDelay(d).setDuration(420).setInterpolator(new OvershootInterpolator(.7f)).start();}
 @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setBackgroundColor(Color.rgb(247,251,255));Ui.setupLightSystemBars(this,root,dp(22),dp(18),dp(22),dp(18));
 TextView fleur=tv("⚜",38,BLUE);root.addView(fleur,new LinearLayout.LayoutParams(-1,dp(48)));TextView logo=tv("NEXUS",42,INK);logo.setTypeface(null,1);logo.setLetterSpacing(.08f);root.addView(logo,new LinearLayout.LayoutParams(-1,dp(56)));TextView duo=tv("DUO // QUÉBEC",14,BLUE);duo.setTypeface(null,1);duo.setLetterSpacing(.22f);root.addView(duo,new LinearLayout.LayoutParams(-1,dp(32)));TextView sub=tv("Vos réseaux. Deux espaces. Une interface.",15,MUTED);root.addView(sub,new LinearLayout.LayoutParams(-1,dp(62)));
 View p1=profile("A","MON ESPACE","Profil 1",0);root.addView(p1,new LinearLayout.LayoutParams(-1,dp(122)));Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,dp(16)));View p2=profile("M","SON ESPACE","Profil 2",1);root.addView(p2,new LinearLayout.LayoutParams(-1,dp(122)));Space flex=new Space(this);root.addView(flex,new LinearLayout.LayoutParams(1,0,1));TextView foot=tv("⚡ PRIVÉ • LOCAL • RESTER DANS NEXUS",11,BLUE);foot.setLetterSpacing(.10f);root.addView(foot,new LinearLayout.LayoutParams(-1,dp(42)));setContentView(root);pop(fleur,0);pop(logo,60);pop(duo,120);pop(p1,220);pop(p2,320);}
 View profile(String letter,String title,String label,int id){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(18),0,dp(18),0);card.setBackground(bg(Color.WHITE,24));card.setElevation(dp(12));TextView av=tv(letter,25,Color.WHITE);av.setTypeface(null,1);GradientDrawable ag=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{BLUE,CYAN});ag.setCornerRadius(dp(50));av.setBackground(ag);card.addView(av,new LinearLayout.LayoutParams(dp(68),dp(68)));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);text.setPadding(dp(18),0,0,0);TextView a=tv(title,17,INK);a.setGravity(Gravity.LEFT);a.setTypeface(null,1);TextView c=tv(label+"  •  Appuyer pour entrer",12,MUTED);c.setGravity(Gravity.LEFT);text.addView(a,new LinearLayout.LayoutParams(-1,dp(34)));text.addView(c,new LinearLayout.LayoutParams(-1,dp(28)));card.addView(text,new LinearLayout.LayoutParams(0,-2,1));TextView arr=tv("›",34,BLUE);card.addView(arr,new LinearLayout.LayoutParams(dp(35),dp(60)));card.setOnTouchListener((v,e)->{if(e.getAction()==0)v.animate().scaleX(.97f).scaleY(.97f).rotationX(3).setDuration(100).start();else if(e.getAction()==1||e.getAction()==3)v.animate().scaleX(1).scaleY(1).rotationX(0).setDuration(180).start();return false;});card.setOnClickListener(v->{getSharedPreferences("nexus",0).edit().putInt("profile",id).apply();startActivity(new Intent(this,DashboardActivity.class));overridePendingTransition(android.R.anim.fade_in,android.R.anim.fade_out);});return card;}
}
